- .firebaserc
- firebase.json
- package-lock.json
- package.json
- projects/components/src/components.module.ts
- projects/components/src/public-api.ts
- projects/doc-lib/src/api-viewer/api-viewer.module.ts
- projects/doc-lib/src/doc-lib.module.ts
- projects/doc-lib/src/documentation-container/documentation-container.module.ts
- projects/doc-lib/src/example-viewer/example-viewer.component.html
- projects/doc-lib/src/example-viewer/example-viewer.component.scss
- projects/doc-lib/src/example-viewer/example-viewer.module.ts
- projects/doc-lib/src/overview-viewer/overview-viewer.component.ts
- projects/doc-lib/src/overview-viewer/overview-viewer.module.ts
- projects/doc-lib/src/source-code-viewer/source-code-viewer.module.ts
- projects/examples/src/app/app-routing.module.ts
- projects/examples/src/app/app.component.ts
- projects/examples/src/app/app.module.ts
- projects/examples/src/components/cliptext/cliptext.examples.module.ts
- projects/examples/src/components/data-exporter/data-exporter.examples.module.ts
- projects/examples/src/components/datagrid/datagrid.example.module.ts
examples app to Firebase
**Why was this change made?**
To solve the following problems with AOT compilation:
Problem:
-Function calls inside the module metadata in DocLib module's static
forRoot function is causing following error which is not useful for
debugging:
ERROR: Function calls are not supported in decorators.
https://www.bennadel.com/blog/3565-providing-module-configuration-using-forroot-and-ahead-of-time-compiling-in-angular-7-2-0.htm
Workaround:
-Use a factory function declared outside the ngModule and call the
constructor 'new' function of doc retriever service inside that. And use
a intermediate injection token to provide the deps required for creation of the factory object.
Problem:
-Importing from barrels within a library is causing the following error:
ERROR in Unexpected …
> Make changes to solve the problems with AOT compilation and deploy

- vcdh5cc.l10n
> Added l10n file

- projects/components/src/datagrid/datagrid.component.html
- projects/components/src/datagrid/datagrid.component.spec.ts
- projects/components/src/datagrid/datagrid.component.ts
- projects/components/src/datagrid/datagrid.module.ts
- projects/components/src/datagrid/directives/component-renderer-outlet.directive.ts
- projects/components/src/datagrid/filters/datagrid-filter.ts
- projects/components/src/datagrid/filters/datagrid-numeric-filter.component.html
- projects/components/src/datagrid/filters/datagrid-numeric-filter.component.scss
- projects/components/src/datagrid/filters/datagrid-numeric-filter.component.spec.ts
- projects/components/src/datagrid/filters/datagrid-numeric-filter.component.ts
- projects/components/src/datagrid/filters/datagrid-string-filter.component.html
- projects/components/src/datagrid/filters/datagrid-string-filter.component.spec.ts
- projects/components/src/datagrid/filters/datagrid-string-filter.component.ts
- projects/components/src/datagrid/index.ts
- projects/components/src/datagrid/interfaces/component-renderer.interface.ts
- projects/components/src/datagrid/interfaces/datagrid-column.interface.ts
- projects/components/src/datagrid/mock-data.ts
- projects/components/src/lib/directives/show-clipped-text.directive.spec.ts
- projects/components/src/utils/filter-builder.ts
- projects/components/src/utils/test/datagrid/datagrid.wo.ts
- projects/components/src/utils/test/datagrid/filter-utils.ts
- projects/components/src/utils/test/filter-builder.spec.ts
- projects/components/src/utils/test/widget-object.ts
- projects/examples/src/components/datagrid/datagrid-filter.example.component.ts
- projects/examples/src/components/datagrid/datagrid-filter.example.module.ts
- projects/examples/src/components/datagrid/datagrid-three-renderers.example.component.ts
- projects/examples/src/components/datagrid/datagrid.examples.module.ts
- projects/examples/src/components/datagrid/mock-data.ts
> Add filtering to Grid columns

- projects/components/src/components.module.ts
- projects/components/src/datagrid/datagrid.module.ts
- projects/components/src/datagrid/filters/datagrid-filter.ts
- projects/components/src/datagrid/filters/datagrid-multiselect-filter.component.html
- projects/components/src/datagrid/filters/datagrid-multiselect-filter.component.spec.ts
- projects/components/src/datagrid/filters/datagrid-multiselect-filter.component.ts
- projects/components/src/datagrid/filters/datagrid-select-filter.component.html
- projects/components/src/datagrid/filters/datagrid-select-filter.component.spec.ts
- projects/components/src/datagrid/filters/datagrid-select-filter.component.ts
- projects/components/src/datagrid/index.ts
- projects/components/src/utils/id-generator/id-generator.spec.ts
- projects/components/src/utils/id-generator/id-generator.ts
- projects/components/src/utils/test/datagrid/filter-utils.ts
- projects/examples/src/components/datagrid/datagrid-filter.example.component.ts
Single select filter
Multi-select filter
Single select filter with custom FIQL
> Add components for data grid filters with selection inputs

- projects/components/src/components.module.ts
- projects/components/src/datagrid/filters/datagrid-multiselect-filter.component.ts
- projects/examples/src/components/datagrid/datagrid.examples.module.ts
The dependency proved to be unnecessary overhead while using the components package in vcd-ui
> Removed Id generator as a dependency from multi select filter component

- projects/components/src/datagrid/filters/datagrid-filter.spec.ts
- projects/components/src/datagrid/filters/datagrid-filter.ts
- projects/components/src/datagrid/filters/datagrid-multiselect-filter.component.spec.ts
- projects/components/src/datagrid/filters/datagrid-multiselect-filter.component.ts
- projects/components/src/datagrid/filters/datagrid-numeric-filter.component.spec.ts
- projects/components/src/datagrid/filters/datagrid-numeric-filter.component.ts
- projects/components/src/datagrid/filters/datagrid-select-filter.component.spec.ts
- projects/components/src/datagrid/filters/datagrid-select-filter.component.ts
- projects/components/src/datagrid/filters/datagrid-string-filter.component.spec.ts
- projects/components/src/datagrid/filters/datagrid-string-filter.component.ts
- Move the emission of changes and construction of form group to the abstract class
- Mke the debounce time overridable
- Add unit tests for abstract Datagrid filter class
> Address comments and add unit tests for DatagridFilter abstract class

- .github/workflows/ci-cd.yml
In addition...
-Install node_modules for every job
-merge the publish next and latest jobs into single jobs
> Remove node_modules cache

- .github/workflows/ci-cd.yml
- projects/components/src/form/index.ts
And add form-checkbox component to public api of components library
> Add npm auth token as environment variable to publish@next jobs

- projects/components/src/datagrid/filters/datagrid-string-filter.component.spec.ts
- projects/components/src/datagrid/filters/datagrid-string-filter.component.ts
This will add on option to pad * at both start and end of a string filter input
> Add wild card at both start and end of a string filter input

- projects/components/src/assets/resources/en.properties
- projects/components/src/datagrid/datagrid.module.ts
- projects/components/src/datagrid/filters/datagrid-numeric-filter.component.html
- projects/components/src/datagrid/filters/datagrid-numeric-filter.component.scss
- projects/components/src/datagrid/filters/datagrid-numeric-filter.component.spec.ts
- projects/components/src/datagrid/filters/datagrid-numeric-filter.component.ts
- projects/components/src/form/form-input/form-input.component.html
- projects/components/src/form/form-input/form-input.component.spec.ts
- projects/components/src/form/form-input/form-input.component.ts
- projects/components/src/utils/test/datagrid/filter-utils.ts
- projects/examples/src/components/datagrid/datagrid-filter.example.component.ts
This will add units dropdown next to number inputs of from and to conditionally. The condition is based on units input.
> Modify datagrid numeric filter input to have units dropdown

- projects/components/src/datagrid/datagrid.component.spec.ts
- projects/components/src/datagrid/datagrid.component.ts
Notify listeners about columns updated event
Add methods to add or remove a column from list grid columns
> Add API to modify grid columns list by adding/removing/updating a column

- projects/components/package.json
This is to update the npm@next package with addColumn and removeColumn
API
> Bump components package version

- projects/components/src/lib/directives/show-clipped-text.directive.spec.ts
- projects/components/src/lib/directives/show-clipped-text.directive.ts
**With mutation observer:**
**Without mutation observer:**
> Remove mutation observer as it is slowing down rendering

- projects/examples/src/app/app.component.html
- projects/examples/src/app/app.component.scss
- projects/examples/src/app/app.component.ts
- projects/examples/src/app/app.module.ts
- projects/examples/src/app/home/home.component.html
- projects/examples/src/app/home/home.component.spec.ts
- projects/examples/src/app/home/home.component.ts
Creates a home page with basic information about the project and how to navigate it.
> Create initial home page

- projects/examples/src/components/activity-reporter/activity-reporter.examples.module.ts
- projects/examples/src/components/form-input/form-checkbox.example.component.ts
- projects/examples/src/components/form-input/form-input-components.examples.module.ts
- projects/examples/src/components/form-input/form-input.example.component.ts
- projects/examples/src/components/form-input/form-select.example.component.ts
- projects/examples/src/components/form-input/number-with-unit-form-input.example.component.ts
Closes #99 and fixes a few other Stackblitz related bugs. Also, separates the two activity reporter examples. 
1. Ran the examples app, navigated to the form input example and made sure the Stackblitz page worked.
2. Navigated to the activity reporter examples and made sure they appeared separately. 
> Fixed bug reported by @ttsvetko and other bugs

- projects/components/src/action-menu/action-menu.component.spec.ts
- projects/components/src/action-menu/action-menu.component.ts
- projects/components/src/action-menu/action-menu.module.ts
- projects/components/src/action-menu/index.ts
- projects/components/src/common/interfaces/action-item.interface.ts
- projects/components/src/common/interfaces/index.ts
- projects/components/src/datagrid/datagrid.component.spec.ts
- projects/components/src/datagrid/datagrid.component.ts
- projects/components/src/datagrid/interfaces/datagrid-column.interface.ts
- tslint.json
ActionItem interface that defines the type of actions that can be given as input to the action menu component.
The component itself with inputs and methods needed for plumbing the model required for rendering the view.
> Interface for the action menu component

- projects/components/package.json
- projects/components/src/form/form-checkbox/form-checkbox.component.html
- projects/components/src/form/form-checkbox/form-checkbox.component.spec.ts
- projects/components/src/form/form-checkbox/form-checkbox.component.ts
- projects/examples/src/components/form-input/form-checkbox.example.component.html
- projects/examples/src/components/form-input/form-checkbox.example.component.ts
Closes the JIRA task https://jira.eng.vmware.com/browse/VDUCC-183
and
GH issue https://github.com/vmware/vmware-cloud-director-ui-components/issues/107
> Associate right label with id of the checkbox input

- projects/components/package.json
- projects/components/src/datagrid/datagrid.component.html
- projects/components/src/datagrid/datagrid.component.scss
- projects/components/src/datagrid/datagrid.component.spec.ts
- projects/components/src/datagrid/datagrid.component.ts
- projects/components/src/datagrid/interfaces/datagrid-column.interface.ts
- projects/components/src/utils/test/datagrid/datagrid.wo.ts
- projects/examples/src/components/datagrid/datagrid-column-width.example.component.html
- projects/examples/src/components/datagrid/datagrid-column-width.example.component.scss
- projects/examples/src/components/datagrid/datagrid-column-width.example.component.ts
- projects/examples/src/components/datagrid/datagrid-column-width.example.module.ts
- projects/examples/src/components/datagrid/datagrid.examples.module.ts
Fixes some reported problems with the datagrid. Namely:
1. Emit an event when selection changed.
2. contextualButtonConfig should be optional
3. Set the height of a column
1. Added tests for selection changed
2. Added tests for width being set.
3. Added tests for optional contextualButtonConfig
> Fixed problems with the datagrid

- projects/components/ng-package.json
- projects/components/package.json
Adding NgxFormly as a dependency in package.json of components as it is required for VcdFormlyModule
> Bump the package version of components package

- projects/components/package.json
- projects/components/src/form/form-input/form-input.component.html
> Revert keyed place holders for form input error translation keys

- projects/components/package.json
- projects/components/src/action-menu/action-menu.component.html
- projects/components/src/action-menu/action-menu.component.ts
- projects/components/src/common/interfaces/action-item.interface.ts
Added the following:
- Text content for inline actions dropdown trigger button
- Additional parameter to ActionItem.availability method
> Dropdown text for inline actions dropdown and additional parameter for ActionItem.availability method

- projects/components/package.json
- projects/components/src/spotlight-search/spotlight-search.component.spec.ts
- projects/components/src/spotlight-search/spotlight-search.component.ts
- projects/components/src/spotlight-search/spotlight-search.module.ts
- projects/examples/src/components/spotlight-search/spotlight-search-example.component.html
- projects/examples/src/components/spotlight-search/spotlight-search-example.component.ts
- projects/examples/src/components/spotlight-search/spotlight-search.example.module.ts
Please take a look at the different commits for more details
> Spotlight search

- projects/components/src/spotlight-search/spotlight-search.component.spec.ts
- projects/components/src/spotlight-search/spotlight-search.service.ts
- projects/examples/src/components/spotlight-search/spotlight-search.example.module.ts
This will insure SpotlightSearchService is singleton and automatically
provided in the app where it is used
> Ensure SpotlightSearchService is provided in `root`

- projects/components/package.json
> Bump ui-components package version

- package-lock.json
- projects/components/package.json
- projects/components/src/action-menu/action-menu.component.html
- projects/components/src/action-menu/action-menu.component.spec.ts
- projects/components/src/action-menu/action-menu.component.ts
Condition to be satisfied to display as dropdown: When there are nested actions or when there are any contextual featured actions
> Make the contextual actions dropdown to be conditionally displayed

- projects/components/package.json
- projects/components/src/action-menu/action-menu.component.ts
This is to avoid mutating original actions list
> Copy actions input before modifying them

- projects/components/package.json
- projects/components/src/action-menu/action-menu.component.html
- projects/components/src/action-menu/action-menu.component.ts
> Display contextual action menu only when there are contextual actions

- projects/components/package.json
- projects/components/src/dropdown/dropdown.component.html
- projects/components/src/dropdown/dropdown.component.ts
> Add class names to fix the failing unit tests

- .github/workflows/ci-cd.yml
> Add a11y branch to list of branches to publish from

- .github/workflows/ci-cd.yml
> Adds next-a11y tag when committing without a tag on a11y branch

- projects/components/package.json
> Create first dummy publishing in a11y for testing

- projects/components/CHANGELOG.MD
From now on, bumpiong the version of our packages should be done in its own commit
making sure that the change is explained in CHANGELOG.md
> Create a template changelog bsed on https://keepachangelog.com/en/0.3.0/

- projects/components/CHANGELOG.MD
- projects/components/package.json
> Version bump to 1.0.0-a11y.2

- projects/components/CHANGELOG.MD
- projects/components/package.json
Bumps the package.json version and updates the changelog for the changes since we bumped to dev.47.
> Bumped the package.json version

- README.md
Changed instructions in Readme.md for opening Examples App in browser. Edited Build section to reflect the change.
> Edit instructions in Examples App section of Readme

- projects/components/CHANGELOG.MD
- projects/components/package.json
Bumps the version and updates the change-log appropriately. 
> Bumped the version of @vcd/ui-components

- projects/components/CHANGELOG.MD
- projects/components/package.json
> Bumping to a11y.3

- projects/components/CHANGELOG.MD
- projects/components/src/components.module.ts
- projects/components/src/form/form-checkbox/form-checkbox.component.html
- projects/components/src/form/form-input/form-input.component.html
- projects/components/src/form/form-select/form-select.component.html
- projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html
- projects/components/src/lib/directives/responsive-input/responsive-input.directive.spec.ts
- projects/components/src/lib/directives/responsive-input/responsive-input.directive.ts
- projects/components/src/lib/directives/responsive-input/responsive-input.module.ts
Allows us to more easily apply the correct CSS classes and it makes
it easier to change it from one place if we chose a different layout.
* This is just a refactoring so testing was the same as https://github.com/vmware/vmware-cloud-director-ui-components/pull/250
* Unit tests created
> Create directive that adds responsive grid CSS classes

- projects/components/CHANGELOG.MD
- projects/components/package.json
> Bump to 1.0.0-a11y.4

- projects/components/CHANGELOG.MD
- projects/components/package.json
> Bump to a11y.5

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/pull_request_template.md
Creates a template for new GH issues.
Uploaded to my forks master branch and tested creating a new issue. Saw that the template appeared correctly.
> Create a template for new GitHub Issues

- projects/components/CHANGELOG.MD
- projects/components/package.json
-   [ ] Bugfix
-   [x ] Version bump
-   [ ] Yes
-   [ ] No
> Bump to 1.0.0-a11y.8

- projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.scss
-   [x] Bugfix
Removed a !important in the scss that was not needed.
Loaded into VCD-UI and made sure the components continued to work.
-   [ ] Yes
- …
> Removed a forgotten !important in the number with unit scss

- projects/components/CHANGELOG.MD
- projects/components/src/form/form-checkbox/form-checkbox.component.html
- projects/components/src/form/form-checkbox/form-checkbox.component.ts
- projects/components/src/form/form-input/form-input.component.scss
- projects/components/src/form/form.scss
- projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html
- projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.scss
- projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts
- projects/examples/src/components/form-input/form-input.example.component.html
- projects/examples/src/components/form-input/form-input.example.component.ts
-   [x] Bugfix
- Added a single line style which sets the following behavior:
- Sequences of whitespace will collapse into a single whitespace.
- Text will wrap when necessary, and on line breaks.
- …
> [a11y] Fix signpost bugs in form components 

- projects/components/src/datagrid/datagrid.component.spec.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
> Fixed bug introduced in tests while merging

- projects/components/CHANGELOG.MD
- projects/components/src/action-menu/action-menu.component.spec.ts
- projects/components/src/action-menu/action-menu.component.ts
- projects/components/src/quick-search/quick-search.component.html
- projects/components/src/quick-search/quick-search.component.spec.ts
- projects/components/src/quick-search/quick-search.component.ts
- projects/components/src/quick-search/quick-search.provider.ts
- projects/examples/src/components/quick-search/quick-search-hide-empty-section-example.component.html
- projects/examples/src/components/quick-search/quick-search-hide-empty-section-example.component.ts
- projects/examples/src/components/quick-search/quick-search-hide-empty-section-example.module.ts
- projects/examples/src/components/quick-search/quick-search.examples.module.ts
-   [ ] Bugfix
There are 2 commits:
1. Add actionsUpdate emitter to ActionMenuComponent
2. Add hideWhenEmpty flag to QuickSearchProvider to control section display when there is no data
-   [ ] Yes
- …
> Quick search improvements

- projects/components/src/dropdown/dropdown-focus-handler.directive.spec.ts
- projects/components/src/dropdown/dropdown.component.spec.ts
- projects/components/src/dropdown/dropdown.component.ts
- projects/components/src/utils/test/widget-object/angular-widget-object.ts
-   [ X ] Tests for the changes have been added (for bug fixes / features)
-   [ N/A ] Examples have been added / updated (for bug fixes / features)
-   [ N/A ] Changelog has been updated
-   [ ] Bugfix
-   [ ] Other... Please describe: Unit tests
Add Unit tests for dropdown focus handler directive that were previously not added. It also modifies the dropdown widget object to extend the new BaseWidgetObject.
- …
> Unit tests for dropdown focus handler directive

- projects/components/CHANGELOG.MD
- projects/components/src/action-menu/action-menu.component.spec.ts
- projects/components/src/action-menu/action-menu.component.ts
-   [ X ] Tests for the changes have been added (for bug fixes / features)
-   [ X ] Changelog has been updated
-   [ ] Bugfix
-   [ X ] Feature
Add a convenience method called `updateDisplayedActions` to the action menu to re-trigger the calculation of visible actions
-   [ ] Yes
-   [ X ] No
> Added a method called `updateDisplayedActions` to action menu

- projects/components/CHANGELOG.MD
- projects/components/package.json
-   [ ] Bugfix
Bumps the version of core components
-   [ ] Yes
-   [x] No
> Bumps the version of core components

- projects/components/CHANGELOG.MD
- projects/components/src/datagrid/datagrid.component.spec.ts
- projects/components/src/utils/test/datagrid/datagrid.wo.ts
- projects/components/src/utils/test/datagrid/filter-utils.ts
- projects/components/src/utils/test/datagrid/vcd-datagrid.wo.ts
- projects/components/src/utils/test/widget-object/angular-widget-object.spec.ts
- projects/components/src/utils/test/widget-object/widget-object.ts
Fixes https://github.com/vmware/vmware-cloud-director-ui-components/issues/308
-   [ ] Bugfix
Adds a method to `BaseWidgetObject` to get the element underlying the current element.
-   [ ] Yes
-   [X] No
> Added a self method to BaseWidgetObject

- projects/components/CHANGELOG.MD
- projects/components/package.json
- tsconfig.json
-   [ ] Bugfix
-   [X] Version bump
> Bumped the version of components

- projects/components/CHANGELOG.MD
- projects/components/package.json
- projects/components/src/quick-search/drawer/drawer.component.html
- projects/components/src/quick-search/drawer/drawer.component.scss
- projects/components/src/quick-search/drawer/drawer.component.ts
- projects/components/src/quick-search/quick-search-registrar.service.ts
- projects/components/src/quick-search/quick-search.component.html
- projects/components/src/quick-search/quick-search.component.scss
- projects/components/src/quick-search/quick-search.component.spec.ts
- projects/components/src/quick-search/quick-search.component.ts
- projects/components/src/quick-search/quick-search.module.ts
- projects/components/src/quick-search/quick-search.provider.ts
- projects/components/src/quick-search/quick-search.service.spec.ts
- projects/components/src/quick-search/quick-search.service.ts
- projects/examples/src/components/quick-search/filters/quick-search-filters.example.component.html
- projects/examples/src/components/quick-search/filters/quick-search-filters.example.component.ts
- projects/examples/src/components/quick-search/filters/quick-search-filters.example.module.ts
- projects/examples/src/components/quick-search/nested-providers/quick-search-nested-providers.example.component.html
- projects/examples/src/components/quick-search/nested-providers/quick-search-nested-providers.example.component.ts
- projects/examples/src/components/quick-search/nested-providers/quick-search-nested-providers.example.module.ts
- projects/examples/src/components/quick-search/quick-search.examples.module.ts
-   [ ] Bugfix
Improves quick search in the following ways:
1. Adds section that are groups of providers. Sections display as headers with smaller provider headers within them.
2. Adds filters that can …
> Added sections and filters to quick search

- projects/components/CHANGELOG.MD
- projects/components/src/datagrid/datagrid.component.spec.ts
- projects/components/src/datagrid/datagrid.component.ts
-   [X] Bugfix
Two way binding has a problem where an event from Clarity, causes the client to send an event back, which causes an infinite loop. 
This change stops the propagation of the events after …
> Fixed datagrid infinite selection loop

- projects/components/CHANGELOG.MD
- projects/components/package.json
- projects/components/src/quick-search/quick-search.component.html
- projects/components/src/quick-search/quick-search.component.scss
- projects/components/src/quick-search/quick-search.component.ts
-   [x] Bugfix
Improves the performance of quick search.
With a dozen or so global search providers registered, quick search was starting to slow down. This changes the HTML so functions are only called …
> Improve the performance of quick search.

- cypress/integration/find-cypress-widget.ts
- projects/components/CHANGELOG.MD
- projects/components/src/utils/test/widget-object/angular/angular-widget-finder.ts
- projects/components/src/utils/test/widget-object/angular/angular-widget-object-element.ts
- projects/components/src/utils/test/widget-object/cypress/cypress-widget-finder.ts
- projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.ts
- projects/components/src/utils/test/widget-object/selector-util.ts
- projects/components/src/utils/test/widget-object/widget-object.ts
Changes made:
- Added dataUiSelector in the FindElementOptions (Find the widget by data ui attribute)
Signed-off-by: Krum Haydushki <khaydushki@vmware.com>
-   [ ] Bugfix
Add method to find widget by …
> Add method to find widget by data ui attribute

- projects/components/CHANGELOG.MD
- projects/components/package.json
- projects/components/src/quick-search/index.ts
- projects/components/src/quick-search/quick-search.component.html
- projects/components/src/quick-search/quick-search.component.spec.ts
- projects/components/src/quick-search/quick-search.component.ts
- projects/components/src/quick-search/quick-search.dataui.ts
- projects/components/src/quick-search/quick-search.wo.ts
- projects/components/src/utils/test/widget-object/angular/angular-widget-object-element.ts
[VDUCC-340 Integration tests for quick search](https://jira.eng.vmware.com/browse/VDUCC-340)
Changes paired with [this GitLab MR](https://gitlab.eng.vmware.com/core-build/vcd_ui/-/merge_requests/3584)
-   [ ] Bugfix
-   [ ] Other... …
> Quick search e2e

- projects/components/CHANGELOG.MD
- projects/components/src/quick-search/quick-search.component.html
- projects/components/src/quick-search/quick-search.component.spec.ts
- projects/components/src/quick-search/quick-search.component.ts
- projects/components/src/quick-search/quick-search.provider.ts
- projects/components/src/quick-search/quick-search.service.spec.ts
- projects/components/src/quick-search/quick-search.service.ts
-   [ ] Bugfix
-   [X] Refactoring (no functional changes, no api changes)
Refactors quick search so that much more logic is contained in the service. This means the service is now responsible for handling the state of the filters, the state of the providers, …
> Refactor quick search service

- projects/components/CHANGELOG.MD
- projects/components/package.json
-   [ ] Bugfix
-   [X] CI related changes
-   [X] Version bump
Sets up the CI/CD pipeline for publishing on the v2 branch.
> First RC for v2

- projects/components/CHANGELOG.MD
- projects/components/package.json
Creates version 2.0 and sets `@latest`
-   [x] No
> Create version 2.0

- projects/components/CHANGELOG.MD
- projects/components/package.json
- projects/components/src/assets/resources/en.properties
- projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts
- projects/components/src/utils/unit/unit-formatter.spec.ts
- projects/components/src/utils/unit/unit-formatter.ts
- projects/components/src/utils/unit/unit.spec.ts
- projects/components/src/utils/unit/unit.ts
- projects/examples/src/components/form-input/number-with-unit-form-input.example.component.html
- projects/examples/src/components/form-input/number-with-unit-form-input.example.component.scss
- projects/examples/src/components/form-input/number-with-unit-form-input.example.component.ts
-   [x] Bugfix
- Introduced new unit for time period.
- Fixed bug in input with unit component - the unit text should be localized.
- Enahced some ts doc texts.
Example app updated with time period …
> Add support for time period unit.

- projects/route-analyzer/CHANGELOG.MD
- projects/route-analyzer/README.md
- projects/route-analyzer/package.json
Previous version (@vcd/route-analyzer@0.0.4) had a mismatch between the version of yargs
in package.json and projects/route-analyzer/package.json
This caused version 0.0.4 to be bad since it uses the version
in projects/route-analyzer/package.json
This was not caught in development because by using npm link to tests changes, modules were being resolved from vcd-ui-common's dist folder instead of the target application, that meant it was reading from node_modules just above the dist folder which did have the correct version of yargs.
To avoid this problem, updated the README to explain that we should use npm install setting package.json's @vcd/route-analyzer entry to point to the dist/route-analyzer.
Please check if your PR fulfills the …
> Fix route analyzer v004

- projects/components/CHANGELOG.MD
Signed-off-by: Tsvetomir Tsvetanov <ttsvetanov@vmware.com>
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> [publish @vcd/ui-components]  3.0.0-dev.2

- projects/components/CHANGELOG.MD
- projects/components/package.json
> [publish @vcd/ui-components] v3.0.0-dev.3

- projects/components/CHANGELOG.MD
- projects/components/package.json
- projects/i18n/package.json
- projects/route-analyzer/package.json
[publish @vcd/ui-components@latest]
[publish @vcd/route-analyzer@latest]
[publish @vcd/i18n@latest]
> Publishing all three libs after Angular upgrade

- projects/components/CHANGELOG.MD
- projects/components/package.json
> Publish @vcd/ui-components@3.0.0-dev.4

- projects/components/src/assets/resources/de.properties
- projects/components/src/assets/resources/es.properties
- projects/components/src/assets/resources/fr.properties
- projects/components/src/assets/resources/it.properties
- projects/components/src/assets/resources/ja.properties
- projects/components/src/assets/resources/ko.properties
- projects/components/src/assets/resources/pt-BR.properties
- projects/components/src/assets/resources/zh-CN.properties
- projects/components/src/assets/resources/zh-TW.properties
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
> This is to check in the L10n changes for VCD 10.4 UI drop1.

- projects/components/CHANGELOG.MD
- projects/components/package.json
- projects/components/src/utils/dom-util.spec.ts
- projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.spec.ts
Includes updates to get unit tests working that were passing before the angular upgrade
-   [x] Tests for the changes have been fixed (for bug fixes / features)
Verified that unit tests run and ran the examples application verifying the datagrid examples
-   [x] No
> [publish @vcd/ui-components] version 4.0.1-dev.1

- projects/components/package.json
- projects/i18n/package.json
- projects/ng-live-docs/package.json
- projects/route-analyzer/package.json
-   [ ] Bugfix
- Changes ui-components version to 13.0.1-dev.1
- Changes i18n version to 13.0.0
- Changes ng-lived-docs version to 0.0.16
- Changes route-analyzer version to 0.0.8
- Updates peer …
> Publish new versions of ui-components, i18n, ng-live-docs and route-analyzer

- projects/components/tsconfig.json
-   [ ] Bugfix
- Added "compilationMode": "partial" in tsconfig.json of components project
- The other project also have this setting, added by the angular update script
Without having …
> Publishing ui-components with ivy partial compilation mode

- projects/components/src/form/form-select/form-select.component.html
- projects/components/src/form/form-select/form-select.component.spec.ts
This reverts commit 5148b2cd16e4f1ec3dc67581df86d502b455fbad.
The original change caused some unit test failures that need to be investigated.
Testing Done:
Re-ran the unit tests for this project.
Bug Number: none
Signed-off-by: Bryan Bozzi <bryanv@vmware.com>
-   [ ] Bugfix
-   [ ] …
> Revert "Fix vcd-form-select loses selection upon changing options."

- projects/components/CHANGELOG.MD
- projects/components/package.json
See CHANGELOG for details. No code changes.
> [publish @vcd/ui-components] 13.0.1-dev.3

- projects/components/CHANGELOG.MD
- projects/components/package.json
See CHANGELOG for details. No code changes.
> [publish @vcd/ui-components] 13.0.1-dev.4

- angular.json
-   [ ] Bugfix
-   [x] Build related changes
Adds back `angular.json`. Nx lint is failing without it.
Run nx lint locally.
-   [ ] Yes
-   [x] No
> Fix CI lint by adding back angular.json

- projects/components/CHANGELOG.MD
- projects/components/package.json
Bumping version only.
-   [ ] Yes
-   [x] No
> Bump ui-components@13.0.1-dev.5

- .github/workflows/publish-components-latest.yml
- .github/workflows/publish-components-next.yml
- .github/workflows/publish-i18n-latest.yml
- .github/workflows/publish-ng-live-docs.yml
- .github/workflows/publish-route-analyzer-latest.yml
We were passing Github's token instead of NPM_TOKEN
-   [x] CI related changes
-   [ ] Yes
-   [x] No
> Pass correct token to publish action

- projects/components/CHANGELOG.MD
- projects/components/package.json
> Bump @vcd/ui-components to 13.0.1-dev.6

- projects/route-analyzer/CHANGELOG.MD
- projects/route-analyzer/package.json
Signed-off-by: Davi Barreto <dbarreto@vmware.com>
-   [x] No
> Bump @vcd/route-analyzer to 0.0.9

- projects/components/CHANGELOG.MD
- projects/components/package.json
> Bump @vcd/ui-components to 13.0.1-dev.7

- projects/route-analyzer/CHANGELOG.MD
- projects/route-analyzer/package.json
> Bump @vcd/route-analyzer to 0.0.10

- package-lock.json
- package.json
- projects/components/CHANGELOG.MD
- projects/components/src/common/subscription/subscription-tracker.spec.ts
- projects/components/src/common/subscription/subscription-tracker.ts
- projects/components/src/datagrid/filters/datagrid-filter.ts
-   [ ] Bugfix
-   [X] Refactoring (no functional changes, no api changes)
It replaces usage of deprecated RxJS APIs with non-deprecated versions, particularly in SubscriptionTracker.
1. I deployed a locally running NPM registry using Verdaccio.
2. I published …
> Implement forward compatibility with RxJS 7.

- projects/components/CHANGELOG.MD
- projects/components/package.json
-   [X] Version bump
-   [X] No
> Bump @vcd/ui-components to 13.0.1-dev.8

- projects/components/CHANGELOG.MD
- projects/components/package.json
Simple version bump. No separate testing.
> Bump ui-components to 13.0.1-dev.9

- projects/route-analyzer/CHANGELOG.MD
- projects/route-analyzer/package.json
- projects/route-analyzer/src/lib/utils.ts
-   [x] Bugfix
Fixes `evaluateNode` so that it only logs the node information when an error occurs
None
> Fix route analyzer error message

- projects/components/src/assets/resources/de.properties
- projects/components/src/assets/resources/es.properties
- projects/components/src/assets/resources/fr.properties
- projects/components/src/assets/resources/it.properties
- projects/components/src/assets/resources/ja.properties
- projects/components/src/assets/resources/ko.properties
- projects/components/src/assets/resources/pt-BR.properties
- projects/components/src/assets/resources/zh-CN.properties
- projects/components/src/assets/resources/zh-TW.properties
Change-Id: I392cf1e8e8c686dd80af57f1ded3120a129e1dd0
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
> This is to check in the L10n changes for VCD 10.4.2 to github.

- projects/components/CHANGELOG.MD
- projects/components/package.json
> Bumping @vcd/ui-components to 13.0.1-dev.10

- .github/workflows/publish-widget-object-latest.yml
No testing done since it's a CI-CD change
> Fix publishing of widget-object

- .github/actions/publish/action.yml
Change `--public` to `--access public`
> Fix publishing of widget-object (part 2)

- projects/components/CHANGELOG.MD
- projects/components/package.json
- projects/components/src/dropdown/dynamic-dropdown-position.directive.ts
Cherry pick #508  onto the angular-13 branch
> Bump UI components 13.0.1 dev.12

- projects/components/CHANGELOG.MD
- projects/components/package.json
> Bump to @vcd/ui-components@15.0.1.dev.2

- projects/components/CHANGELOG.MD
- projects/widget-object/CHANGELOG.MD
- projects/widget-object/package.json
Version bump for @vcd/widget-object@0.0.2
Had [previously](#516) added entries to the wrong changelog
> Bump to @vcd/widget-object@0.0.2

- .github/workflows/ci-cd.yml
- .gitignore
- package-lock.json
- package.json
- projects/components/CHANGELOG.MD
- projects/components/package.json
- projects/examples/project.json
- projects/examples/src/app/app.module.ts
- projects/ng-live-docs/scripts/index.js
- projects/route-analyzer/src/cli.ts
The compilation was failing because we were compiling files outside the src folder. I am not sure what has changed that broke it.
Also, we forgot to add @compodoc/compodoc when removing https://www.npmjs.com/package/rbradford-compodoc which had some custom fixes that had already been added to the main compodoc repo.
-  [x] Bugfix
Fix running `nx build examples`. We were getting the following error.
> ./projects/examples/src/app/app.module.ts:19:0-72 - Error: Module not found: Error: Can't resolve '../../gen/components-doc.json' in '/Users/nvladimirovi/Desktop/git-repos/vmware-cloud-director-ui-components/projects/examples/src/app'
> ./projects/examples/src/app/app.module.ts:20:0-68 - Error: Module not found: Error: Can't resolve '../../gen/examples-doc.json' in …
> Fix nx build examples

- projects/components/CHANGELOG.MD
- projects/components/package.json
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
> Bump @vcd/ui-components to 15.0.1-dev.6

- projects/components/CHANGELOG.MD
- projects/components/package.json
> Bump @vcd/ui-components to 15.0.1-dev.10
