vmware/vmware-cloud-director-ui-components

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/datagrid/datagrid.module.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/gen/components-compodoc-documentation/documentation.json, projects/examples/src/components/datagrid/datagrid-detail-row.example.component.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
Adds the capability for clients of the library to set the details content in rows that allows the rows to expand.
Added a unit test that tests that the rows have all the appropriate buttons to expand, and that the row will expand when you click the button.
Also, added an example that shows the behavior.
=> Implemented details for grid rows

.travis.yml, package-lock.json, package.json, projects/components/src/cliptext/cliptext.component.spec.ts, projects/doc-lib/package-lock.json, projects/doc-lib/src/doc-lib.module.ts
**Why?**
Deploy examples app to Github pages and publish the 2 libraries
**What?**
_Pages deployment:_
Build the examples app in aot mode and use that artifact from the ./dist to deploy. This is being done instead of production build config for building the app because, the prod config is resulting in a package([isuue](https://github.com/angular/angular-cli/issues/11915)) that is not working with the Compodoc JSONs.
_NPM publish:_
The publish stage jobs are conditional based on following conditions:
`($TRAVIS_REPO_SLUG = "vmware/vmware-cloud-director-ui-components") && 
("$TRAVIS_TAG" =~ ^LIB_NAME-v\d.\d.\d$) && 
("$TRAVIS_TAG" != "")`
They should be published to @vcd scope in the registry
=> Update the CI-CD with Pages deployment and npm registry publishing

.travis.yml, package-lock.json, package.json, projects/examples/src/app/app.module.ts, tsconfig.json
**What and Why was this change made?**
Travis CI example app build job is failing because of the following
problems:
doc-lib module node dependencies: They had to be manually installed by
going into the doc-lib project folder creating extra complication to the
script phase of doc-lib package build. So those dependencies are
duplicated in the main package.json dependencies so that they can be
installed as main node modules and any executables can be executed right
from the main node-module's .bin
Compodoc documentation generation: The components build scripts are
modified to use the compodoc executable in the main node_module's json
AOT build of examples: This is failing right now with a strange error:
Please add doc container component to a module. So using regular build
for the examples. …
=> Fix the Travis CI-CD errors

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/datagrid/interfaces/datagrid-column.interface.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/src/components/datagrid/datagrid-sort.example.component.ts, projects/examples/src/components/datagrid/datagrid-sort.example.module.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
Exposes information in the gridRefresh event that allows us to sort the columns of the datagrid on the server side. Only supports sorting by 1 column at a time. Supports both ascending and descending sorting. 
Added a unit test that tests that a column can be both sorted ascending and descending. Also, added an example that shows a table with two columns and what happens when they are sorted.
Due to a bug recently fixed in Clarity, when a column is sorted then another is sorted, an icon appears on both columns even though the table is only sorted by the later column.
=> Added sorting capabilities to datagrid columns

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/src/components/datagrid/datagrid-css-classes.example.component.ts, projects/examples/src/components/datagrid/datagrid-detail-row.example.component.ts, projects/examples/src/components/datagrid/datagrid-pagination-example.component.ts, projects/examples/src/components/datagrid/datagrid-pagination-example.module.ts, projects/examples/src/components/datagrid/datagrid-row-select.example.component.ts, projects/examples/src/components/datagrid/datagrid-show-hide.example.component.ts, projects/examples/src/components/datagrid/datagrid-sort.example.component.ts, projects/examples/src/components/datagrid/datagrid-three-renderers.example.component.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
Adds support for pagination to the datagrid. Allows the user to input data for the pagination type and how it should be translated. Exposes the pagination information through the gridRefresh event. 
Added unit tests that test the input properties and the output information from gridRefresh. Also, added an example that shows a massive grid and how the pagination interacts with it.
=> Added pagination support

.travis.yml
Outputs the i18n.json into the examples dist folder during the Travis stage.
Built the app as described in the travis file and then served the examples app from a Python server and made sure the translations appeared correctly.
=> Build translations for examples in travis

.travis.yml, package.json
Fixes the deployment process in Travis to rely on the build process rather than rebuilding in the deployment step. This allows steps like `generate-example-translations` and `build-components-doc` to only happen once.
Changed the destination repo to point to my fork, and ran the build through travis. It deployed correctly to https://ryan-bradford.github.io/vmware-cloud-director-ui-components. 
=> Fixed deployment step for travis

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.scss, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/datagrid/datagrid.module.ts, projects/components/src/datagrid/interfaces/datagrid-column.interface.ts, projects/components/src/datagrid/renderers/index.ts, projects/components/src/datagrid/renderers/linked-text-renderer.component.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/src/assets/our-translations.json, projects/examples/src/components/datagrid/datagrid-link.example.component.ts, projects/examples/src/components/datagrid/datagrid-link.example.module.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts, tslint.json
Adds action buttons to the datagrid. There are two types of buttons - 
1. Global Buttons, which always appear at the top of the datagrid and whose visibility does not depend on the row currently selected.
2. Contextual buttons, which can appear either at the top of the grid or next to each row, and whose visibility does depend on the row(s) currently selected.
There are also various options for visibility:
1. Hide: When the button is inactive, it will not be shown anywhere.
2. Disable: when the button is inactive, it will be shown as disabled.
Exception: in the dropdown, all buttons will always be shown (just potentially disabled).
Added an example that shows all features of the buttons in action. Also, added unit tests that test the features as described above.
=> Added action buttons to the datagrid

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/datagrid/datagrid.module.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/src/components/datagrid/datagrid-height.example.component.ts, projects/examples/src/components/datagrid/datagrid-height.example.module.ts, projects/examples/src/components/datagrid/datagrid-pagination-example.component.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
Allows the user to set the desired height of their datagrid. If the height is set, the datagrid (all parts included) will be limited to the given height. If the height is not set, the datagrid will fill to expand the parent. If the parents height is not fixed, the datagrid will grow to the necessary size.
Also, added the "Magic" page size option. This will calculate the optimal page size given the height of the datagrid. If the height is not set, it will not attempt to calculate the page size, and will instead default to 5.
Added unit tests to test both the grid height input and the "Magic" pagination setting. Also, added an example to show the datagrid filling up the whole parent container, and an example showing the datagrid being limited to it's set height and calculating the correct …
=> Implemented grid height + magic pagination

package.json, projects/components/package.json, projects/doc-lib/src/stack-blitz-writer.service.ts, projects/i18n/ng-package.json, projects/i18n/package.json
Manually published new version of @vcd-ui/components and the first
version of @vcd/i18n since the examples require it.
Duplicated messageformat dependency so it can be included when
publishing @vcd/i18n
Updated stackblitz template to load i18n translations. See https://stackblitz.com/edit/vcd-ui-cc-starter-clarity-v8-yhe4yg
Clicked play on the first example from our three components
=> Fix play button by passing the correct template ID to SB

package-lock.json, package.json, projects/components/src/common/subscription/index.ts, projects/components/src/common/subscription/subscription-tracker.mixin.spec.ts, projects/components/src/common/subscription/subscription-tracker.mixin.ts, projects/components/src/common/subscription/subscription-tracker.spec.ts, projects/components/src/common/subscription/subscription-tracker.ts, projects/components/src/public-api.ts, projects/examples/src/app/app.module.ts, projects/examples/src/components/subscription/subscription-tracker-mixin.example.component.ts, projects/examples/src/components/subscription/subscription-tracker-mixin.example.module.ts, projects/examples/src/components/subscription/subscription-tracker.examples.module.ts, projects/i18n/src/lib/service/message-format-translation-service.ts
Adds in a subscription tracker that can manage multiple subscriptions at once. It also adds in a subscription tracker mixin that allows a class to automatically gain the methods in the subscription tracker and will unsubscribe from these subscriptions when it's destroyed.
Added unit tests for both the mixin and the tracker class. Also, added an example that shows how to apply this mixin to a class:
=> Added in a subscription tracker

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.scss, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/src/components/datagrid/datagrid-detail-row.example.component.ts, projects/examples/src/components/datagrid/datagrid-header.example.component.html, projects/examples/src/components/datagrid/datagrid-header.example.component.ts, projects/examples/src/components/datagrid/datagrid-header.example.module.ts, projects/examples/src/components/datagrid/datagrid-height.example.component.html, projects/examples/src/components/datagrid/datagrid-height.example.component.scss, projects/examples/src/components/datagrid/datagrid-height.example.component.ts, projects/examples/src/components/datagrid/datagrid-link.example.component.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
Allows the user to set a header property on the datagrid which will automatically put a `h3` on the top of the grid with the header text.  Does not put it within the clr-datagrid, so this will not affect the magic pagination or grid height change.
Found a few copy-paste errors in the examples folder, so I changed those to reflect the actual purpose of the examples. 
Added unit tests to test both the header property existing, not-existing, and changing. Also, added an example to show the header.
=> Allows the user to set a header on the datagrid

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/datagrid/interfaces/datagrid-column.interface.ts, projects/components/src/lib/directives/show-clipped-text.directive.spec.ts, projects/components/src/lib/directives/show-clipped-text.directive.test-helper.ts, projects/components/src/lib/directives/show-clipped-text.directive.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/src/components/datagrid/datagrid-cliptext.example.component.html, projects/examples/src/components/datagrid/datagrid-cliptext.example.component.ts, projects/examples/src/components/datagrid/datagrid-cliptext.example.module.ts, projects/examples/src/components/datagrid/datagrid-three-renderers.example.module.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
Grid cells will automatically enable cliptext using the show-cliptext directive. This is always the case unless the client sets disableCliptext to true within the column configuration.
Added an example that shows text being clipped for normal renderers and component renderers. It also shows cliptext being disabled. Also, added tests to test if disabling cliptext actually removes the directive. 
1. I chose to make cliptext size be always large. Should this be an input option?
=> Implemented auto cliptext in the grid cells

projects/components/src/datagrid/filters/datagrid-select-filter.component.spec.ts, projects/components/src/datagrid/filters/datagrid-select-filter.component.ts, projects/components/src/lib/directives/show-clipped-text.directive.spec.ts, projects/examples/src/components/datagrid/datagrid-filter.example.component.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
Make changes to the select filter to give it custom FIQL capability.
When this switch is turned on, select filter's getValue does not do any FIQL formatting.
=> Add custom FIQL filter

projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/datagrid/datagrid.module.ts, projects/components/src/datagrid/interfaces/datagrid-column.interface.ts, projects/components/src/datagrid/renderers/bold-text-renderer.wo.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/components/src/utils/test/datagrid/vcd-datagrid.wo.ts, projects/components/src/utils/test/widget-object.ts, projects/examples/src/app/components/show-clipped-text/sizing/show-clipped-text-sizing-example.component.html, projects/examples/src/components/datagrid/datagrid-activity-reporter.example.component.html, projects/examples/src/components/datagrid/datagrid-activity-reporter.example.component.ts, projects/examples/src/components/datagrid/datagrid-activity-reporter.example.module.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
Added the activity reporter on top of the grid. Exposes it as a field of the datagrid, and also allows button handlers to return a promise that triggers the activity reporting. 
Added unit tests to test that it works with the datagrid. In addition, added an example to show how to return a promise from the button handler and trigger reporting.
1. Datagrid example is a little abstract.
2. Searching this.root.parent for h3 in the datagrid.wo.ts file to find the header feels strange.
3. Should we provide a better export from the datagrid to monitor activities outside of the grid buttons?
=> Enabled activity reporting on the grid

.github/workflows/ci-cd.yml, projects/components/package.json
The if condition expressions to perform jobs only on the master branch were wrong and the condition expressions are corrected.
It didn't fail during my testing because of the `on:` condition for the workflow at top of the yaml file. Previously, it was only running on pushes to master branch and I changed it just before finalizing my changes and didn't test the condition.
Test Run: https://github.com/ps37/vmware-cloud-director-ui-components/runs/528355791?check_suite_focus=true
=> Fix the master branch condition expression for CI jobs

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/datagrid/filters/datagrid-filter.ts, projects/components/src/datagrid/interfaces/datagrid-column.interface.ts, projects/components/src/utils/test/datagrid/filter-utils.ts, projects/examples/src/components/datagrid/datagrid-filter.example.component.ts
As part of this PR, also the following changes are added:
Remove default filter
Make the subscription tracker mixin extent 'class {}' instead of Object
**Demo:**
=> Add not sortable flag to grid column

projects/components/package.json, projects/components/src/common/activity-reporter/index.ts, projects/components/src/lib/directives/index.ts, projects/components/src/lib/directives/show-clipped-text.directive.spec.ts, projects/components/src/lib/directives/show-clipped-text.directive.test-helper.ts, projects/components/src/lib/directives/show-clipped-text.directive.ts, projects/components/src/public-api.ts, projects/components/src/utils/test/index.ts
Fixes the cliptext tests so that they always pass, regardless of if the window is focused or it is running in GH Actions.
Necessary Changes made:
1. transitionend doesn't seem to run when the window is unfocused. So I made the tip static object exported (but not exported from the public API) and directly called the transitionEnd method from the test.
2. mutationObserver threw an error that hostElement could not be found because tip.currentDirective is undefined. So, I added a check to make sure tip.currentDirective is defined.
Those were the two issues causing the test failures.
Improvements Made:
1. Removed most of the await timeout(...) to speed up the tests. Only two were required to still be there and are both commented (and we're commented originally before this change). 
Ran the …
=> Fixed cliptext tests.

.github/workflows/ci-cd.yml, angular.json, projects/doc-lib/package.json
Add `--access public` to publish@next jobs and
Add GitHub username and email to deploy phase of angular cli build
Test run below shows that publish@next of doc-lib is not using stale cache package.json and it also shows successfully deployed GitHub pages:
https://github.com/ps37/vmware-cloud-director-ui-components/actions/runs/66668658
=> Fix publish@next and gh-pages-deploy jobs

projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.scss, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/datagrid/interfaces/datagrid-column.interface.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/components/src/utils/test/index.ts, projects/components/src/utils/test/widget-object.ts, projects/examples/src/components/datagrid/datagrid-activity-reporter.example.component.ts, projects/examples/src/components/datagrid/datagrid-link.example.component.ts
1. Improves the methods in the datagrid widget object for full testing capabilities.
2. Uses class and removed ID for the buttons
3. Featured + featured count defaults to all the buttons when undefined
4. Fixed the alignment of "..." in the button dropdown
5. Column visibility defaults to SHOWN
1. Updated the unit tests + used in VCD-UI
1. Switched to clrDgItems. When this is not used (and instead we use ngFor), selection in VCD-UI breaks. The code for the clrDgItems directive doesn't suggest that this directive enforces any client side sorting or filtering (https://github.com/vmware/clarity/blob/master/src/clr-angular/data/datagrid/datagrid-items.ts), but I'm not totally sure.
=> Changes to Datagrid + Widget Object

.github/workflows/ci-cd.yml, angular.json, package.json, projects/components/src/components.module.ts, projects/doc-lib/src/stack-blitz-writer.service.ts, projects/examples/src/components/activity-reporter/banner-activity-reporter.example.module.ts, projects/examples/src/components/activity-reporter/spinner-activity-reporter.example.module.ts, projects/examples/src/components/data-exporter/data-exporter.example.module.ts, projects/examples/src/components/datagrid/datagrid-activity-reporter.example.component.html, projects/examples/src/components/datagrid/datagrid-activity-reporter.example.component.ts, projects/examples/src/components/datagrid/datagrid-activity-reporter.example.module.ts, projects/examples/src/components/datagrid/datagrid-cliptext.example.module.ts, projects/examples/src/components/datagrid/datagrid-css-classes.example.module.ts, projects/examples/src/components/datagrid/datagrid-detail-row.example.module.ts, projects/examples/src/components/datagrid/datagrid-filter.example.module.ts, projects/examples/src/components/datagrid/datagrid-header.example.module.ts, projects/examples/src/components/datagrid/datagrid-height.example.module.ts, projects/examples/src/components/datagrid/datagrid-link.example.module.ts, projects/examples/src/components/datagrid/datagrid-pagination-example.module.ts, projects/examples/src/components/datagrid/datagrid-row-icon.example.module.ts, projects/examples/src/components/datagrid/datagrid-row-select.example.module.ts, projects/examples/src/components/datagrid/datagrid-show-hide.example.module.ts, projects/examples/src/components/datagrid/datagrid-sort.example.module.ts, projects/examples/src/components/error/error-banner.example.module.ts, projects/examples/src/components/loading/loading-indicator.example.module.ts, projects/examples/src/components/subscription/subscription-tracker-mixin.example.module.ts, projects/i18n/package.json, projects/i18n/src/lib/i18n.module.ts
Updates the examples application to import only the ComponentsModule rather than the individual modules. Also, makes it so the Stackblitz writer service pre-loads the template. 
Ran the unit tests + made sure the examples app was still functional. 
=> Examples improvements + stackblitz pre-loading

projects/examples/src/main.ts, projects/i18n/package.json, projects/i18n/src/lib/i18n.module.spec.ts, projects/i18n/src/lib/i18n.module.ts, projects/i18n/src/lib/utils/index.ts, projects/i18n/src/lib/utils/tokens.ts
Removed the BOOTSTRAP_DETAILS injection token and instead uses LOCALE_ID provided by Angular.
1. Updated the examples app to use LOCALE_ID and made sure it functions in both dev and prod modes. 
2. Updated VCD_UI to use LOCALE_ID and made sure it still functions. 
3. Did a search, and there are no references to BOOTSTRAP_DETAILS in our project anymore.
=> Removed BOOTSTRAP_DETAILS

package-lock.json, package.json, projects/i18n/package.json, projects/i18n/src/lib/i18n.module.spec.ts, projects/i18n/src/lib/service/message-format-translation-service.spec.ts
In messageformat 2.0.0, they introduced a breaking change where single-quote became an escape character our of interpolation. This change downgrades messageformat to use the same version as listed in VCD-UI's package.json.
Added a unit test to test that the interpolation now works. Also, confirmed that this test failed when using messageformat 2.3.0. 
=> Fixed messageformat version

projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/examples/src/components/datagrid/datagrid-detail-row.example.component.ts
Adds back in a trackBy clause to ngFor and fixes the related selection bugs that it causes.
There is a known and open bug in Clarity that using trackBy and refreshing the data breaks the select all functionality (https://github.com/vmware/clarity/issues/2265). This is due to orphaned selected items/rows in the datagrid. 
The fix to the problem is either to remove trackBy (which we tried and cannot do), use clrDgItems (which we tried and cannot do), or follow the solution in this Stackblitz linked from the above GitHub issue (https://stackblitz.com/edit/issue-2265-workaround?file=src%2Fapp%2Fapp.component.ts). This solution involves adding a detectChanges when you update the grid data and manually calling grid.rows.notifyOnChanges. Not totally ideal, but it seems to be the only way. 
1. …
=> Adds trackBy to datagrid rows ngFor

README.md, package.json, projects/components/README.md, projects/doc-lib/README.md, projects/i18n/README.md
Updated the READme files to include more up-to-date information. Namley:
1. Fixed broken/inaccurate links.
2. Replaced ng... commands with npm run.. commands because we occasionally add additional logic, such as in the case of npm run build:components, or npm start
3. Updated the i18n documentation to be much more specific and informative.
=> Fixed inconsistencies in the READme.md files

projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/datagrid/directives/component-renderer-outlet.directive.ts, projects/examples/src/components/datagrid/datagrid-detail-row.example.component.ts, projects/examples/src/components/datagrid/datagrid-detail-row.example.module.ts
Adds the ability for a row detail to use the [clrLoading] directive to make the detail contents lazy loaded. It does this by requiring the row detail to be input as a component rather than a template, and then when it creates the component it provides the LoadingListener as a provider.
1. Added a unit test to test the LoadingListener provider
2. Updated the existing detail row test to work.
3. Ran the app with a lazy loaded detail row and assured it works.
=> Implemented lazy loading detail expansions

projects/components/package.json, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.spec.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts
Disabling the formControl of number-with-form input component should disable the underlying input and select t form controls.
This functionality was missing before. Found this while integrating the component in vcd-ui.
=> Add disabled functionality to number with form input control value accessor

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/src/components/datagrid/datagrid-loading-placeholder.example.component.html, projects/examples/src/components/datagrid/datagrid-loading-placeholder.example.component.ts, projects/examples/src/components/datagrid/datagrid-loading-placeholder.example.module.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
Makes it so the emptyGridPlaceholder input is displayed on the grid placeholder.
Added unit tests to test that the placeholder is only displayed when the grid is not loading but the data is present.
Added an example to show the loading + placeholder abilities.
=> Implemented a placeholder on the datagrid

projects/examples/src/assets/our-translations.json, projects/examples/src/main.ts, projects/i18n/package.json, projects/i18n/src/lib/i18n.module.spec.ts, projects/i18n/src/lib/i18n.module.ts
Fixes a bug where translations were not properly used in any language other than English when the application loaded the I18nModule as forRoot. This was because we did not have the correct type of data input to the singletonFactory.
- Changed Unit tests to test some language other than English. Verified this test failed without this change. 
- Ran VCD-UI with this new I18n module and in the dev environment switched the locale to DE. Made sure the translations were correct/present. Verified the translations displayed incorrectly without this change. 
=> Use LOCALE_ID for singleton factory

package-lock.json, package.json, projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/src/components/datagrid/datagrid-detail-pane.example.component.ts, projects/examples/src/components/datagrid/datagrid-detail-pane.example.module.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
1. Adds support for the detail pane in Clarity 3.
2. Fixes a bug reported by Bryan where if we set the `[pagination]` before the grid is rendered, it is overriden and reset to the default. This results in pagination mostly not working.
1. Added an example to show that the detail pane functions in the datagrid.
2. Added a test to make sure you can click the expand button to show the content.
=> Support Clarity 3 detail pane

projects/components/package.json, projects/components/src/form/form-select/form-select.component.spec.ts, projects/components/src/form/form-select/form-select.component.ts
The selectedOption of FormSelect component is returning undefined when there is a mismatch between string and number types of values between option.value and formControl.value even though the values are equal.
For Example: `this.options.find(option => option.value === this.formControl.value);` resulting in...
1000 === "1000" or "1000" === 1000
=> Fix selectedOption returning undefined because of mismatching primitives

projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/examples/src/components/datagrid/datagrid-detail-row.example.component.ts
The user can now decide to have all rows expanded by setting isRowExpanded to true. The default is to have all rows collapsed.
Updated the datagrid example to show how the input works.
Testing Done:
Added two more tests for when the input is true and false.
Signed-off-by: Xuanvinh Vu <xvu@vmware.com>
=> Add isRowExpanded input to vcd-datagrid

projects/route-analyzer/package.json, projects/route-analyzer/tsconfig.lib.json
Previous attempt to publush to npm repository failed with error:
> ERROR: Trying to publish a package that has been compiled by Ivy. This is not allowed.
> Please delete and rebuild the package, without compiling with Ivy, before attempting to publish.
=> Disable Ivy for route-analyzer

projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts
This commit has the following changes:
- Make the DG take a string as input for pagination translation instead of a callback
These changes affect VCD UI and they are made in the following MR:
https://gitlab.eng.vmware.com/core-build/vcd_ui/merge_requests/2097
=> Replace pagination translation call back with a string input

package-lock.json, package.json, projects/components/package.json, projects/components/src/components.module.ts, projects/components/src/index.ts, projects/components/src/spotlight-search/index.ts, projects/components/src/spotlight-search/spotlight-search-result.ts, projects/components/src/spotlight-search/spotlight-search.component.html, projects/components/src/spotlight-search/spotlight-search.component.scss, projects/components/src/spotlight-search/spotlight-search.component.spec.ts, projects/components/src/spotlight-search/spotlight-search.component.ts, projects/components/src/spotlight-search/spotlight-search.module.ts, projects/components/src/spotlight-search/spotlight-search.provider.ts, projects/components/src/spotlight-search/spotlight-search.service.spec.ts, projects/components/src/spotlight-search/spotlight-search.service.ts, projects/components/src/utils/test/widget-object.ts, projects/examples/src/app/app.module.ts, projects/examples/src/components/spotlight-search/spotlight-search-example.component.html, projects/examples/src/components/spotlight-search/spotlight-search-example.component.ts, projects/examples/src/components/spotlight-search/spotlight-search.example.module.ts, projects/examples/src/components/spotlight-search/spotlight-search.examples.module.ts
The Spotlight Search component is inspired by the Spotlight Search functionality in Mac OSX (cmd+space) and the Search Everywhere in IntelliJ (shift+shift)
This is the basic implementation consisting of:
- angular component
- search service
- search provider interface
- search results interface
The commit also includes
- documentation
- full feature live doc example
- unit tests
=> Create spotlight search component

projects/route-analyzer/package.json, projects/route-analyzer/src/lib/utils.ts
If typescripts are different versions then evaluation may not succeed.
Also the typescript library is now a peer dependency since route-analyzer
is not only a standalone tool but also an angular package library,
providing AppRoute interface.
All of this implies that typescript should not be bundled with route-analyzer.
=> Use the same typescript version for @wessberg/ts-evaluator as the route-analyzer

projects/components/package.json, projects/components/src/datagrid/datagrid.component.ts
Fixed a bug in the datagrid where if the grid was set to empty, then set to have items, it might appear as empty. This is because of a bug in Clarity https://github.com/vmware/clarity/issues/4692
Loaded this build of components into VCD-UI and sorted, filtered, and paginated in the orgs list screen. All of these actions worked as intended. 
=> Fixes a bug in the datagrid where filtering, pagination, sorting might make it empty

README.md, projects/components/package.json, projects/components/src/spotlight-search/spotlight-search.component.scss
Fixes an issue in VCD-UI where all modals were appearing without a header. 
Fixes #130 
Linked to VCD-UI and made sure the modals display correctly.
=> Restrict the css only to the spotlight search component

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/src/components/datagrid/datagrid-detail-pane.example.component.ts
Makes it so the header of the detail pane is a callback that takes in a record and returns a string, instead of just a string.
Updated the unit tests and examples to pass the header as a callback.
=> Detail pane header is now dynamic

projects/components/package.json, projects/components/src/action-menu/action-menu.component.html, projects/components/src/action-menu/action-menu.component.scss, projects/components/src/action-menu/action-menu.component.ts, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.scss, projects/components/src/dropdown/dropdown.component.html
**What was the change?**
Tweak the styles of action menu component so that it can be used in vcd_ui inside the datagrid components
**Why was this change made?**
Currently when the action menu is used inside datagrid components in vcd_ui, they don't show up properly
**Testing Done:**
Screenshots of the vcd_ui grids in which these changes are applied is attached in this MR: https://gitlab.eng.vmware.com/core-build/vcd_ui/merge_requests/2209
Note: Also, That MR will be pushed only after this PR is merged.
=> Change styles of action menu for using it inside the datagrid components

projects/components/package.json, projects/components/src/action-menu/action-menu.component.ts
Add a switch to turn off calculation of actions availability if they are already calculated outside
=> Calculate actions availability switch

package-lock.json, projects/components/package.json, projects/components/src/action-menu/action-menu.component.ts
Use calculateActionsAvailability switch before using the selectedEntities to determine availability and display of contextual actions
=> Change the contextual actions availability and display logic

projects/components/package.json, projects/components/src/action-menu/action-menu.component.html, projects/components/src/action-menu/action-menu.component.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/dropdown/dropdown.component.html, projects/components/src/dropdown/dropdown.component.ts, projects/examples/src/components/action-menu/action-menu.example.component.ts
The end 2 end tests in vcd ui are failing because of missing class names on action items inside action dropdowns. So, added those class names
Added class names to action item objects in ActionMenuExample component and made sure that those classes get added to the class list of action button html element
=> Add class name to action items VcdDropdown

projects/components/package.json, projects/components/src/action-menu/action-menu.component.spec.ts, projects/components/src/action-menu/action-menu.component.ts, projects/components/src/datagrid/datagrid.component.ts
- To avoid mutating _actionDisplayConfig being used internally by the ActionMenuComponent to control the view
- To avoid mutating the config object being passed as input from the calling component using ActionMenuComponent
Added unit tests to test the above 2 scenarios
=> Make changes to not mutate action display config objects

projects/examples/src/components/action-menu/action-menu.example.component.html, projects/examples/src/components/action-menu/action-menu.example.component.ts
As the html is in the same .ts file, it is not being highlighted right now in the examples web app.
Verified that the examples website highlights the HTML
=> Separate the template into a .html file

projects/components/package.json, projects/components/src/utils/test/angular-widget-driver.spec.ts, projects/components/src/utils/test/angular-widget-driver.ts, projects/components/src/utils/test/angular-widget-finder.ts, projects/components/src/utils/test/base-widget-object.ts, projects/components/src/utils/test/cypress-widget-driver.ts, projects/components/src/utils/test/cypress-widget-finder.ts, projects/components/src/utils/test/index.ts, projects/components/src/utils/test/widget-object.ts
Creates a new WidgetObject pattern so that widget objects can be used in both Cypress and Angular tests. All new WidgetObjects should now extend the BaseWidgetObject which will give all the necessary methods to test features.
1. WidgetDriver interface
- this is the interface for an object that knows how to interact with the dom. Currently we have three CypressWidgetDriver (cypress), AngularWidgetDriver (angular), BaseWidgetDriver (delegation to another).
2. BaseWidgetDriver
- All new WidgetObjects should extend this to gain the ability to interact with the dom for any arbitrary testing framework.
3. WidgetFinders(s)
- Given a FindParams, locates the specific WidgetDriver and instantiates the WidgetObject. Two Widget Finders, one for Cypress, one for Angular
1. Added the Angular Widget …
=> Created new WidgetObject pattern for Cypress and Angular tests

projects/components/package.json, projects/components/src/spotlight-search/spotlight-search.component.html, projects/components/src/spotlight-search/spotlight-search.component.scss, projects/components/src/spotlight-search/spotlight-search.component.spec.ts, projects/components/src/spotlight-search/spotlight-search.component.ts, projects/components/src/utils/dom-util.spec.ts, projects/components/src/utils/dom-util.ts, projects/examples/src/components/spotlight-search/spotlight-search-example.component.ts, projects/examples/src/components/spotlight-search/spotlight-search-no-title-example.component.html, projects/examples/src/components/spotlight-search/spotlight-search-no-title-example.component.ts, projects/examples/src/components/spotlight-search/spotlight-search.example.module.ts, projects/examples/src/components/spotlight-search/spotlight-search.examples.module.ts
- use `section` instead of `div`
- use `h5` instead of `div`
- scroll to selected item to ensure it is always visible
- always display section title if such has been provided
Up to now if there was just one search provider, i.e. one section
its title was not shown. This leads to confusion when providers
are added and removed on the fly. In that case one section may apear
without a title and at the next moment when there is another provider
this section will have a title.
- add `role="button"` for better ARIA support
- add DOM util class, currently with `scrollToElement` functionality
- new example for a simgle section with no title and many items
- create instance of mouse trap within the constructor to eliminate the
usage of change detector
- refactor code to make it easier to follow
=> Spotlight search improvements

projects/i18n/package.json, projects/i18n/src/lib/loader/translation-loader.ts, projects/i18n/src/lib/pipe/translation-pipe.spec.ts, projects/i18n/src/lib/pipe/translation-pipe.ts, projects/i18n/src/lib/service/message-format-translation-service.spec.ts, projects/i18n/src/lib/service/message-format-translation-service.ts
Fixes three issues with the i18n library:
1. The translateAsync method would emit an untranslated string prior to emitting a translated string while the translations are loading.
2. The fallbackLocale was not used with async translations.
3. The translationPipe was causing memory issues by creating too many subscriptions. 
1. Added unit tests to test the first two issues. 
2. Fixed old unit tests that weren't running. 
3. Loaded into VCD UI and tested the app both in english and German
4. Ran the examples app and made sure translations worked in English.
=> Fixed i18n issues

projects/components/package.json, projects/components/src/assets/resources/en.properties
Fixes the default translation key for the number with unit form input. Right now the error message appears as "Only numbers in the range of undefined to undefined are allowed". 
Ran the app locally and verified that the message appears as:
=> Fixed the number with unit form default error translation

projects/components/package.json, projects/components/src/spotlight-search/spotlight-search-result.ts, projects/components/src/spotlight-search/spotlight-search.component.spec.ts, projects/components/src/spotlight-search/spotlight-search.component.ts
It is useful to know when the spotlight search component is calling
the item handler. One specific use case is for doing analytics.
This code change ensures ResultActivatedEvent is emitted when the
item handler is called.
=> Provide resultActivated emitter

projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts
Fixes the problem where the trackBy function was not working on the vcd-datagrid and selection was lost on every refresh. This is specifically due to a bug in Clarity (https://github.com/vmware/clarity/issues/3936) where the trackBy on the row might come from somewhere else in the grid. We initially only thought this would happen if the trackBy was unset on the row, but it seems like it can even override it in certain cases. To fix this, I separated out the action menu into it's own template to separate the provider chain. With this fix, the trackBy in the action menu stays where it should be.
Closes https://github.com/vmware/vmware-cloud-director-ui-components/issues/156
1. Added a unit test and verified that this unit test fails before my change.
2. Build library and put into VCD_UI, …
=> Fixed datagrid trackBy

projects/components/package.json, projects/components/src/action-menu/action-menu.component.html, projects/components/src/action-menu/action-menu.component.ts, projects/components/src/data-exporter/csv-exporter.service.spec.ts, projects/components/src/data-exporter/csv-exporter.service.ts, projects/components/src/data-exporter/data-exporter.component.spec.ts, projects/components/src/data-exporter/data-exporter.component.ts
Make `ExportColumn.displayName` optional. If there is no displayName, the default value to display column will be `fieldName`.
When exporting data, if the given value is a Javascript object, it will be converted to JSON string.
Enable `static-action-separator` when there is static action. Static actions will align right without static featured action.
Test done:
- unit tests: add and pass test cases for `CsvExporterService` and `DataExporterComponent`.
- manually: static actions can align right when there is no static featured action.
=> Make ExportColumn.displayName optional and convert object to JSON string when exporting.

projects/i18n/package.json, projects/i18n/src/lib/service/mock-translation-service.spec.ts, projects/i18n/src/lib/service/mock-translation-service.ts
Fixes a problem where a getter was not being compiled to a readonly in the .d.ts files. This causes the error that `error TS1086: An accessor cannot be declared in an ambient context.`. This is because of a TS breaking change https://github.com/microsoft/TypeScript/issues/33939.
Inspected the TS output and made sure it did not contain any getters.
=> Fixes a problem due to a breaking TS change

projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/examples/src/components/datagrid/datagrid-row-select.example.component.ts
The grid now has two generics:
B  - an object that contains only the single property that identifies this record. So for example a { href: string }. This is the same property that your trackBy MUST return.
R - the record itself. This type extends B.
The property datagridSelection is now a two way binding that accepts/returns a (R | B)[]. If you want to set some list of preselected items, create a list of B's and bind to datagridSelection . datagridSelection will then continue to output a type B for all unloaded entities, but will output a full type R for any entity that has been loaded to the grid.
This grid also has an input preserveSelection that defaults to false. preserveSelection must be set to true for selection to be maintained across multiple pages/filters.
The default behavior is …
=> Two way binding for selection

projects/components/package.json, projects/components/src/data-exporter/data-exporter.component.html, projects/components/src/data-exporter/data-exporter.component.spec.ts, projects/components/src/data-exporter/data-exporter.component.ts
Display `fieldName` on 'export all columns' of data exporter modal when there is no `displayName`.
**Why this change made?**
After making `displayName` an optional property, for those export columns only having `fieldName`, the column selection on data exporter will display empty text. This change could make it display fieldName.
Test Done:
- Add a test case to verify `clr-dropdown-menu` and `column-container` display `fieldName` when there is no `displayName`.
- manually: after opening the data exporter modal and unchecking 'export all columns', the export columns only having `fieldName` display `fieldName` now.
Before this change:
After this change:
=> Display fieldName on 'export all columns' of data-exporter

projects/components/package.json, projects/components/src/data-exporter/data-exporter.component.html, projects/components/src/data-exporter/data-exporter.component.spec.ts, projects/components/src/data-exporter/data-exporter.component.ts
Add a helper method to get display name.
Use WidgetObject pattern to rewrite a test case and remove the `querySelector` codes.
**Why this change made?**
There are several places having display name with code `col.displayName || col.fieldName`, which is duplicated.
For test cases, queries should be hidden behind the widget wrapper and `querySelector` would break WidgetObject pattern.
**Test done:**
- Pass unit tests.
- manually: The behavior of data exporter doesn’t change.
=> Remove duplicated codes about optional displayName and use WidgetObject pattern to rewrite a data exporter test case

projects/components/src/action-search-provider/action-search.provider.spec.ts, projects/components/src/action-search-provider/action-search.provider.ts, projects/components/src/assets/resources/en.properties, projects/components/src/quick-search/quick-search-result.ts, projects/components/src/quick-search/quick-search.component.html, projects/components/src/quick-search/quick-search.component.scss, projects/components/src/quick-search/quick-search.component.spec.ts, projects/components/src/quick-search/quick-search.component.ts, projects/components/src/quick-search/quick-search.provider.ts, projects/components/src/quick-search/quick-search.service.spec.ts, projects/examples/src/components/quick-search/quick-search-no-title.example.component.ts, projects/examples/src/components/quick-search/quick-search-sync-async.example.component.html, projects/examples/src/components/quick-search/quick-search-sync-async.example.component.ts, projects/examples/src/components/quick-search/quick-search.examples.module.ts
The search result of a provider can return a subsection of the total number
of items that match the criteria. Such an example is a backend query. The ideal
behavior is to be able to load the next page but we are still not there to implement this.
The current solution for this scenario is to show the number of the found items,
the total number of items and a warning message to the user.
The changes include:
- modify the QuickSearchResult to contain items, page, pageSize and total
- update the search component to
-- show the partial results found
-- display a warning message if there are more items
- add new SearchProvider for the sync-async example
=> Display total number of results per search provider.

projects/components/package.json, projects/components/src/dropdown/dropdown.component.spec.ts, projects/components/src/dropdown/dropdown.component.ts, projects/examples/src/assets/our-translations.json, projects/examples/src/components/action-menu/action-menu.example.component.ts
Open the nested menus at 2nd level in the action menu component by hovering over the dropdown items instead of having to click them
Some of the menus like actions in vapp/vms now are 2 levels deep and having to click the menu item to open nested dropdowns is a little annoying
Tested the functionality in examples app
Unit tests for the mouse event handling methods - https://jira.eng.vmware.com/browse/VDUCC-324
=> Add functionality to open sub menus on hover

projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts
Fixes two bugs with the detail row and pane.
1. The detail config was constantly being set because we were recreating a new config every time change detection was run on the datagrid. This change makes it so the config will not be changed unless the entity reference changes.
2. The detail pane was not correctly following the trackBy. This change patches in a fix from a Clarity PR: https://github.com/vmware/clarity/pull/5035
1. Added a console.log in setting config and ran the detail pane locally. Verified it is only set now when the record changes.
2. Added unit tests to test each bug above.
3. Loaded into VCD_UI, navigated to the trusted certificates page, opened a row, sorted, and verified the detail pane was still open. 
My linter seems to have changed some stuff. Should I undo this? …
=> Fixes bugs in the detail pane and row

package.json, projects/components/package.json, projects/components/src/assets/resources/en.properties, projects/components/src/form/form.module.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.scss, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.spec.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts, projects/examples/src/components/form-input/form-input-components.examples.module.ts, projects/examples/src/components/form-input/number-with-unit-form-input-unitless.example.component.html, projects/examples/src/components/form-input/number-with-unit-form-input-unitless.example.component.scss, projects/examples/src/components/form-input/number-with-unit-form-input-unitless.example.component.ts, projects/examples/src/components/form-input/number-with-unit-form-input-unitless.example.module.ts, projects/examples/src/components/form-input/number-with-unit-form-input.example.component.html, projects/examples/src/components/form-input/number-with-unit-form-input.example.component.scss, projects/examples/src/components/form-input/number-with-unit-form-input.example.component.ts
Some of the changes are:
* Add new examples, enhance existing ones
* Enable the component to work with no units
* Remove internal validation but enable external ones only
* Add new validator: NumberWithUnitsFormValidatorsFactory.isInRange
* (in this component only) support not only `{ [key]: true }` error, but also `{ [key]: any }`
This gives much more flexibility when translating errors 
* Use error style of the input, but show errors outside of the input component
for 2 reasons:
a) use the new supported format of errors and
b) align the error not only under the input element but also under the unit dropdown
* Add initialValueUnit to prevent finding the best match for the initial value
* min/max values of the inner input are calculated according to the selected unit
* remember last real …
=> Number with unit input - various fixes

projects/components/package.json, projects/components/src/lib/directives/show-clipped-text.directive.ts
This bug occurs because of a timing issue. It happens when you show the cliptext, move off, and just as the cliptext bubble is disappearing, hover over the element and immediately leave again. What happens is that the directive is cleared from the first hiding, and then the leave event for the singleton from the second event fires before the enter event for the second event. This causes the error seen.
Before this fix, I was able to easily reproduce the error on the datagrid example. After this fix, I could not get the error to happen again. 
Fixes https://github.com/vmware/vmware-cloud-director-ui-components/issues/120
=> Fixed 'Cannot read mouseoutDelay of null'

projects/components/package.json, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts
Fixes a small bug with the number with unit form where the best unit was not being calculated unless the checkbox was unlimited.
Loaded into VCD_UI and ran their unit tests.
=> Fixed a small bug with number with unit

projects/components/package.json, projects/components/src/datagrid/datagrid.component.scss
On `vcd-datagrid`, space between action menu and `clr-datagrid` is a bit wide, which should be updated to match CSS with screens using clr-datagrid` directly.
**Test done:**
Now space between action and datagrid is the same as screens using `clr-datagrid`.
=> Fix wide space on vcd-datagrid between action and datagrid (vmware#204)

projects/components/package.json, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts, projects/components/src/utils/unit/unit.ts
1. Fixes a bug where the findBestUnit method did not work correctly
2. Fixes a bug when on editing an input without an unlimited checkbox, the best unit was not selected. 
Loaded into VCD_UI.
1. Created a Vapp from a template to show that best unit selection now works for their memory input. 
2. Edited a Kubernetes policy on a Org VDC to show their validators working with the correct units.
=> Fixes bugs with the number with unit input

projects/components/package.json, projects/components/src/quick-search/quick-search.component.scss
The reason of this change is, `--clr-global-hover-color` makes hover color of quick search result item on dark theme the same as for the regular theme. Change it to `--clr-tree-link-hover-color` could make it same as edit blocking task modal, which looks good for both default theme and dark theme.
**Test done:**
On Dark theme:
- Open quick search modal
- Write some characters
- Observe that hover color is not the same as for the regular theme and now it looks good on dark theme
Default Theme:
Dark Theme:
Cassini Theme:
=> Fix quickSearch mouse over color on dark theme

projects/components/package.json
This change updates ui-components version which is missing from previous PR https://github.com/vmware/vmware-cloud-director-ui-components/pull/211, and enables changes about quickSearch mouse over color.
=> Update ui-components version.

projects/components/package.json, projects/components/src/action-search-provider/action-search.provider.spec.ts, projects/components/src/action-search-provider/action-search.provider.ts, projects/examples/src/components/action-menu/action-menu-search-pause-and-unpause.example.component.html, projects/examples/src/components/action-menu/action-menu-search-pause-and-unpause.example.component.ts, projects/examples/src/components/action-menu/action-menu-search-pause-and-unpause.example.module.ts, projects/examples/src/components/action-menu/action-menu.example.component.ts, projects/examples/src/components/action-menu/action-menu.examples.module.ts
- Displaying `?undefined` in the action search result section. This is happening because of not filtering out the `separator` objects from the action list.
- Actions are not shown after the entity is done loading. The search text has to be changed for them to get updated.
- Verified that the vm and vapp entity details screens of vcd ui don't show errors 1 and 2
- Unit tests for newly added code in action search provider
- Example showcasing the added pause and unpause functionality of action search
=> Fix actions not shown until entity is loaded bug and action search result availability calculation bug

projects/components/package.json, projects/components/src/data-exporter/csv-exporter.service.spec.ts, projects/components/src/data-exporter/csv-exporter.service.ts, projects/components/src/data-exporter/data-exporter.component.spec.ts
Microsoft for Excel for the Mac was not able to detect the UTF encoding
on its own, so it didn't show non-ASCII characters.
* Using our examples container, exported a CSV where the header contained Japanese characters
* Open the CSV with Excel and make sure you can see the Japanese characters.
=> Add UTF-8 BOM mark to CSV exported file.

projects/components/src/form/form-select/form-select.component.spec.ts, projects/components/src/form/form-select/form-select.component.ts
If you don't want any option pre-selected on a form-select, its value should be null. However, that was throwing an NPE.
* Unit tests added that failed before the fix.
* This problem only happens if you are calling the component's `selectedOption`
=> Allow null values for form select

projects/components/package.json, projects/components/src/quick-search/quick-search.component.spec.ts, projects/components/src/utils/test/widget-object.ts
Some libraries like mousetrap use deprecated, read-only keyboard event properties
like `which`. This makes it impossible to use the general `new KeyboardEvent`
mechanism of creating the event and dispatching it later. To overcome this
we have used `Object.defineProperty`.
In addition to this, the method signature was also changed to allow more versatile
approach of setting different event properties.
This functionality is related entirely to unit testing
=> Modify sendKeyboardEvent to be more versatile

projects/components/src/dropdown/dropdown.component.spec.ts, projects/components/src/dropdown/dropdown.component.ts
Adds unit tests to cover the logic that opens and closes drop-down menus using `mouseover` and `mouseout` events
=> Unit tests for dropdown menu mouse event handlers

projects/components/src/common/error/error-banner.component.html, projects/components/src/common/error/error-banner.component.spec.ts, projects/components/src/common/error/error-banner.wo.ts
Screen Readers were not able to read the content of the error banner.
To fix this ARIA role is added:
role='alert'  - whenthe `alertType` is danger
role='status' - for all other cases
- unit tests
- manual tests: use VoiceOver MAC util and verify that the error message has been read
=> [a11y] Add ARIA role to the ErrorBannerComponent

projects/components/src/form/base-form-control.ts, projects/components/src/form/form-input/form-input.component.html, projects/components/src/form/form-input/form-input.component.spec.ts
- Added aria-required which depends on the 'showAsterisk' input.
The screen reader will announce if the field is required.
- Added aria-describedby for either errors or description in the input subtext.
- Added ids to the description and error elements using the IdGenerator.
- Fixed the 'for' attribute binding to the input label
Testing done:
- Tested with NVDA on the examples project
- Unit tests for each case
=> [a11y] Add aria attributes to the Form Input component

projects/components/src/dropdown/dropdown.component.ts
Nested-menus that are opened on hover are being closed for example when they are accidentally clicked upon. This is not a very good UX.
Looking at other dropdowns like... in Mac OS and Microsft outlook, we found out that the nested menus that are opened on hover are not reacting to mouse clicks. So, taking the inspiration from there, I have done something similar by preventing mouse clicks from happening on the nested menu triggers.
=> Prevent nested menus that are opened on hover from closing when clicked

projects/components/src/action-menu/action-menu.component.html, projects/components/src/dropdown/dropdown-focus-handler.directive.ts, projects/components/src/dropdown/dropdown-focus-handler.service.ts, projects/components/src/dropdown/dropdown.component.html, projects/components/src/dropdown/dropdown.component.spec.ts, projects/components/src/dropdown/dropdown.component.ts, projects/components/src/dropdown/dropdown.module.ts
Because the focus handling logic through the keyboard is not working correctly on the vcd-dropdown component. This is happening because the Clarity code is not able to recognize nested Vcd dropdown as content children. So we decided to write our own focus handling logic
Disable the Claritys focus handling logic and then write our own focus handling logic. A directive to link the menu items and then service for updating the currently focused item. There is only one instance of this per root dropdown.
=> Add custom focus handling logic for dropdown menu

projects/components/src/dropdown/dropdown.component.html
The disabled attribute on dropdown menu buttons is not making them focusable. Instead, Clarity suggests using the [clrDisabled] attribute for the disabled visual style and ARIA attribute when needed
Replaced the disabled attribute with clrdisabled on dropdown menu buttons
=> Replace [disabled] with [clrDisabled] on action menu buttons

projects/components/src/form/form-checkbox/form-checkbox.component.html, projects/components/src/form/form-select/form-select.component.html
Fix for attribute on label - form select
And aria-describedby - form select, checkbox
Add aria-required form select
I tested manually on Windows 10 in Mozilla Firefox and Chrome with NVDA and Developer Tool. Click on input reader reads label. On error reader reads message.
Signed-off-by: Tsvetomir Tsvetanov <ttsvetanov@vmware.com>
=> [a11y] Labels is not associated with the form select element

cypress/integration/examples/data-exporter.spec.ts, package-lock.json, package.json, projects/components/src/utils/test/widget-object/angular-widget-finder.ts, projects/components/src/utils/test/widget-object/cypress-widget-finder.ts, projects/components/src/utils/test/widget-object/cypress-widget-object.ts, projects/components/src/utils/test/widget-object/find-cypress-widget.ts, projects/components/src/utils/test/widget-object/index.ts, projects/components/tsconfig.spec.json, tsconfig.json
When we loaded the Cypress types in our library via either `types: [..., "cypress"]` in the tsconfig or via `import * from 'cypress'` in a given file, it loads the `global namespace Cypress`. This also loads the global namespace for Chai (and Sinon and a few other libraries). This namespace was then loaded whenever a user imported anything from `@vcd/ui-components`. This meant that in unit tests Jasmine and Chai would have a clash on definitions. 
Force users to supply the Cypress types externally. Meaning, `CypressWidgetFinder` now has one generic type T of what type the underlying locator will find (documentation more clear in the code). In the scope of our library, we don't have to load Cypress anymore because the typing is supplied externally. Then in the stepdef file, all the user …
=> Fixes the type clash between Jasmine and Chai in unit tests

projects/components/CHANGELOG.MD, projects/components/src/form/form-checkbox/form-checkbox.component.html, projects/components/src/form/form-input/form-input.component.html, projects/components/src/form/form-input/form-input.component.scss, projects/components/src/form/form-select/form-select.component.html, projects/components/src/form/form.scss, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.scss, projects/examples/src/components/form-input/form-input.example.component.html, projects/examples/src/components/form-input/number-with-unit-form-input.example.component.html
Followed Clarity's pattern of setting CSS grid classes. This allows
form inputs to be visible when zoom is set to 200% by moving labels and inputs to be on their own lines under small resolutions.
* The aside content is moved into the clr-input-container so that is always stays next to it
* number with unit input added some custom CSS to keep the select dropdown for the unit, and the hint signpost on the same line
Check the following pages.
* [vcd-form-input](https://vmware.github.io/vmware-cloud-director-ui-components/formInputs/example)
* [vcd-form-select](https://vmware.github.io/vmware-cloud-director-ui-components/formSelect/documentation)
* [vcd-number-with-unit-input](https://vmware.github.io/vmware-cloud-director-ui-components/numberWithUnitFormInput/example/number-with-unit-form-in …
=> [A11y] Make form inputs responsive

package-lock.json, package.json, projects/components/CHANGELOG.MD
Update `ng-live-docs` version to 0.0.8 to use generation schematic `ng-live-docs:add-example`, which make it easy to create examples for the entity details container.
Detail about schematic: https://github.com/vmware/live-docs/pull/11
=> Update `ng-live-docs` version to 0.0.8 to enable schematics

projects/components/src/form/form-input/form-input.component.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.spec.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.widget-object.ts
Usability requirements imply the focus to be on the input element when 'unlimited checkbox' is
deselected in order to be easier for the user to modify the value.
In the live examples for the number with unit input verify that the focus is moved to the imput element
when the unlimited checkbox is unchecked - either with a mouse click or with the keyboard
=> [a11y] Set the focus on input element when unlimited is unchecked

projects/components/src/common/error/error-banner.component.scss
Issue #172 The banner component margins were 24px and are now 0. 
* Go to http://localhost:4200/errorBanner/example
* Verify that banner aligns with button above it
Signed off by Ria Mahoney mpatrice@vmware.com
=> Remove margins from error banner

projects/components/CHANGELOG.MD, projects/components/src/form/form-checkbox/form-checkbox.component.html, projects/components/src/form/form-checkbox/form-checkbox.component.scss, projects/components/src/form/form-checkbox/form-checkbox.component.ts, projects/components/src/form/form-input/form-input.component.html, projects/components/src/form/form-input/form-input.component.scss, projects/components/src/form/form-select/form-select.component.html, projects/components/src/form/form.module.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html, projects/components/src/lib/directives/responsive-input/responsive-input.directive.ts, projects/examples/src/components/form-input/form-checkbox.example.component.html
Also fixed some a bad previous commit:
* vcdResponsiveInput was added as a class name instead of an attribute
* Module for vcdResponsiveInput was incorrectly setup
* Make sure we only query for input labels and containers that are immediate children of clr-form-control
- Verified the checkbox input hint's for both the regular checkbox and the toggle buttons.
- Installed this version in VCD's UI to make sure modules were working.
=> [a11y] Add hints to checkbox component

projects/components/CHANGELOG.MD, projects/components/src/assets/resources/en.properties, projects/components/src/datagrid/filters/datagrid-numeric-filter.component.spec.ts, projects/components/src/form/base-form-control.ts, projects/components/src/form/form-input/form-input.component.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.scss, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.spec.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.widget-object.ts, projects/examples/src/components/form-input/number-with-unit-form-input-unitless.example.component.html, projects/examples/src/components/form-input/number-with-unit-form-input-unitless.example.component.scss, projects/examples/src/components/form-input/number-with-unit-form-input-unitless.example.component.ts, projects/examples/src/components/form-input/number-with-unit-form-input.example.component.html, projects/examples/src/components/form-input/number-with-unit-form-input.example.component.scss, projects/examples/src/components/form-input/number-with-unit-form-input.example.component.ts
This fixes an issue where the form control's value was null if the user input could not be parsed as a number. We did not display any validation error to the user explaining that the input is invalid.
`form-input` uses an internal default validator that checks for HTML's [validity](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState) for `badInput`
We also chose to reimplement the HTML for number-with-unit with raw clarity HTML instead of `vcd-form-*` implementations. Trying to combine the different fields to look correctly took a lot of CSS. This allowed us to use fewer CSS hacks and easier control over the HTML.
* Displays "Invalid number" if user types `e`, `1e`, `-e` 
* In Firefox, anything is allowed so typing abc also displays "Invalid number"
* Type -1 into warn level
* …
=> [a11y] Show validation errors when users type invalid numbers

projects/components/src/form/form-select/form-select.component.html, projects/components/src/form/form-select/form-select.component.spec.ts, projects/examples/src/app/home/home.component.spec.ts
* Go to http://localhost:4200/formSelect/example
* Verify that error icon does not appear when user arrives on the page
* Verify that error icon does not appear when user selects an option from the drop-down
* Verify that error icon DOES appear when user fails to select an option from the drop-down
* Test to verify no icon shows when page loads
* Test to verify icon shows when user selects invalid option
* Test to verify no icon shows when user selects valid option
Signed-off-by: Ria Mahoney <mpatrice@vmware.com>
=> Adds error icon to vcd-form-select

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/action-menu/action-menu.component.html, projects/components/src/dropdown/dropdown-focus-handler.directive.ts, projects/components/src/dropdown/dropdown-focus-handler.service.ts, projects/components/src/dropdown/dropdown.component.html, projects/components/src/dropdown/dropdown.component.spec.ts, projects/components/src/dropdown/dropdown.component.ts, projects/components/src/dropdown/dropdown.module.ts
This Pull request is similar to the PR created to merge into the master branch at https://github.com/vmware/vmware-cloud-director-ui-components/pull/264. However, This PR is created separately because the accessibility fixes(`DropdownFocusHandlerDirective`, `DropdownFocusHandlerService`) that are already checked into the `master` branch didn't make it into the `a11y` branch and hence this PR contains duplicate changes.
Please review the changes at https://github.com/vmware/vmware-cloud-director-ui-components/pull/264 to approve this PR.
Fix the following a11y issues in the action menu component:
- Navigating using up & down arrows on the action menu pop-up is making the underlying page scroll. The underlying page should not scroll.
- Pressing the Space/Enter keys on nested menus is not …
=> [a11y branch]Fix accessibility issues on Action menu component

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/dropdown/dropdown-focus-handler.directive.ts, projects/components/src/dropdown/dropdown-focus-handler.service.ts, projects/components/src/dropdown/dropdown.component.html, projects/components/src/dropdown/dropdown.component.spec.ts, projects/components/src/dropdown/dropdown.component.ts, projects/examples/src/app/components/action-menu/contextual-actions/action-menu-contextual-actions-example.component.ts
Fix the following a11y issues in the action menu component:
- Navigating using up & down arrows on the action menu pop-up is making the underlying page scroll. The underlying page should not scroll.
- Pressing the Space/Enter keys on nested menus is not closing the action menu. Pressing those keys from anywhere on the menu should activate the button and then close the menu.
- Pressing the Esc key on the menu should just close the menu.
- Navigation using arrow keys on a menu with separators is not working.
Tested the action menu in VM and Vapp action menus:
In the examples app:
=> [master branch]Fix accessibility issues on Action menu component

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts
This was causing problems revealed by unit tests because writeValue can depend on @Input values
which are not set before ngOnInit
Ran unit tests for ui-components and for VCD's internal vcd_ui project
=> Make sure writeValue for number-with-unit is not called before ngOnInit

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/data-exporter/data-exporter.wo.ts, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/filters/datagrid-numeric-filter.component.spec.ts, projects/components/src/datagrid/renderers/bold-text-renderer.wo.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/components/src/utils/test/datagrid/filter-utils.ts, projects/components/src/utils/test/datagrid/vcd-datagrid.wo.ts, projects/components/src/utils/test/widget-object.ts, projects/components/src/utils/test/widget-object/angular-widget-object.spec.ts, projects/components/src/utils/test/widget-object/angular-widget-object.ts, projects/components/src/utils/test/widget-object/widget-object.ts
- Rewrote `VcdDatagridWidget` and `ClrDatagridWidget` using new Widget Object pattern.
- Rewrote datagrid component unit tests using new `ClrDatagridWidget`.
- Rewrote helper method `createDatagridFilterTestHelper` and `createDatagridFilterTestHelperWithFinder` using new Widget Object.
- Added convenience methods `sendKeyboardEvent`, `classes`, and `parent` to `TestElement`.
- Removed `WithGridBoldRenderer`. The `getBoldText` is implemented in `ClrDatagridWidget.getCellStrong`.
Ran unit tests and assured that all the tests passed.
=> Rewrite `ClrDatagridWidget` with new Widget Object

projects/components/CHANGELOG.MD, projects/components/src/lib/directives/responsive-input/responsive-input.directive.ts
The reason for this issue is, in a responsive input, default clr grid classes for label and container are `clr-col-md-2` and `clr-col-md-10`, which are fine for most places. But when width for the host element row is small, there is no enough space for label.
This PR updates `ResponsiveInput` to add grid classes based on host element's width.
When host's width is less than 768px:
When host's width is bigger than 768px:
=> Update responsive input to increase label's width when container's width is small

projects/components/CHANGELOG.MD, projects/components/src/components.module.ts, projects/components/src/form/form.module.ts, projects/components/src/lib/directives/alternative-text/alternative-text.directive.spec.ts, projects/components/src/lib/directives/alternative-text/alternative-text.directive.ts, projects/components/src/lib/directives/alternative-text/alternative-text.module.ts
-   [x] Bugfix
- Introduces alternative-text directive that sets the 'alt' attribute on the inner 'svg'
- on the examples, inspected the error icon and verified that it has an empty 'alt' attribute
- …
=> [a11y] Fix no alternative text on input error icons

projects/components/CHANGELOG.MD, projects/components/src/form/form-select/form-select.component.html, projects/components/src/form/form-select/form-select.component.scss
-   [x] Bugfix
- Add css style `white-space: normal` to label in `vcd-form-select` to make label text wrap
- Fix bug where labels is not associated with …
=> Fix bug where label text is not wrapped and labels is not associated with the 'Access Level' combo box

projects/components/CHANGELOG.MD, projects/components/package.json
-   [ ] Bugfix
Bump a11y version to 1.0.0-a11y.9:
Added blank alternative text to all svgs inside clr-icon elements
Fixed issues where label text is not …
=> Bump a11y version to 1.0.0-a11y.9

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts
*  The problem appeared to be that this.datagrid.selection.currentSingle was set to undefined instead of an empty array when the user clears their selection.
* The template was getting datagridSelection from Clarity $event but it should have come from the getter.
* [$event] is an array of undefined. 
* Now if this.datagrid.selection.currentSingle is undefined, the logic in the getter handles for that and returns the empty array.
* Added unit test to verify that when the selection is cleared an empty array is emitted.
* Added unit test to verify that when the selection is cleared the getter for the current selection returns an empty array.
Fixes: #233 
Signed-off-by: Ria Mahoney <mpatrice@vmware.com>
=> Using datagridSelection getter to emit datagrid selection changes

projects/components/CHANGELOG.MD, projects/examples/src/components/quick-search/quick-search-content-projection.example.component.ts, projects/examples/src/components/quick-search/quick-search-content-projection.example.module.ts, projects/examples/src/components/quick-search/quick-search.examples.module.ts
-   [x] Bugfix
The Quick Search 'Content Projection' example was not opening on stackblitz with an error in the console.
In order to run an example on stackblitz the component name should be matching …
=> Fix Quick Search 'Content Projection' example not opening on Stackblitz

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/components/src/utils/test/datagrid/filter-utils.ts, projects/components/src/utils/test/datagrid/vcd-datagrid.wo.ts, projects/components/src/utils/test/widget-object/angular-widget-object.ts
-   [ ] Bugfix
- Added function `queryElements` to enable `TestElement` to query children elements by css selector
- Removed functions in …
=> Updated `ClrDatagridWidget` to remove functions that are specific to `VcdDatagrid`

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/form/base-form-control.ts, projects/components/src/form/form-checkbox/form-checkbox.component.html, projects/components/src/form/form-input/form-input.component.html, projects/components/src/form/form-select/form-select.component.html, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html, projects/components/src/index.ts, projects/components/src/lib/directives/responsive-input/responsive-input.directive.spec.ts, projects/components/src/lib/directives/responsive-input/responsive-input.directive.ts
-   [ ] Bugfix
-   [x] Unit Tests added
Allow users of form controls to disable the behavior that makes labels be on the same line when there's enough real estate.
This is needed when the …
=> Allow disabling responsive input directive on form controls

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/action-search-provider/action-search.provider.ts, projects/components/src/quick-search/quick-search.component.spec.ts, projects/components/src/quick-search/quick-search.component.ts, projects/components/src/quick-search/quick-search.provider.ts, projects/components/src/quick-search/quick-search.service.spec.ts, projects/components/src/utils/common-util.spec.ts, projects/components/src/utils/common-util.ts, projects/examples/src/app/components/action-menu/action-menu.examples.module.ts, projects/examples/src/app/components/action-menu/search-debounce/action-menu-search-debounce.example.component.html, projects/examples/src/app/components/action-menu/search-debounce/action-menu-search-debounce.example.component.scss, projects/examples/src/app/components/action-menu/search-debounce/action-menu-search-debounce.example.component.ts, projects/examples/src/app/components/action-menu/search-debounce/action-menu-search-debounce.example.module.ts, projects/examples/src/app/components/action-menu/search/action-menu-search-example.component.ts, projects/examples/src/components/quick-search/quick-search-content-projection.example.component.ts, projects/examples/src/components/quick-search/quick-search-sync-async.example.component.ts, projects/examples/src/components/quick-search/quick-search-sync-async.example.module.ts
-   [YES] Tests for the changes have been added (for bug fixes/features)
-   [YES] Examples have been added / updated (for bug fixes / features)
-   [YES] Changelog has been updated
-   [ ] Bugfix
-   [x] Other... Please describe: Simplify for the caller of a search provider to debounce the calling of the search function
Simplify for the caller of a search provider to debounce the calling of the search function …
=> Add de-bouncing logic to the quick search functionality

projects/components/CHANGELOG.MD, projects/components/src/action-menu/action-menu.component.ts, projects/examples/src/app/components/action-menu/with-separators/action-menu-with-separators.example.component.html
-   [ X ] Tests for the changes have been added (for bug fixes / features)
-   [ X ] Changelog has been updated
-   [ ] Bugfix
-   [ X ] Other... Please describe: Api changes
Some of the components calculate the visibility of actions by themselves without having to rely on the ActionMenuComponent. So, in the past, a boolean input to …
=> Remove calculateActionAvailability input

projects/components/package.json
I forgot to bump the components package version with the PR https://github.com/vmware/vmware-cloud-director-ui-components/pull/290 that got merged into master. This change is just to bump the number in components/package.json
=> Forgot to bump the package version with previous merge

cypress/integration/examples/data-exporter.spec.ts, projects/components/CHANGELOG.MD, projects/components/src/data-exporter/data-exporter.component.spec.ts, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/dropdown/dropdown-focus-handler.directive.spec.ts, projects/components/src/dropdown/dropdown.component.spec.ts, projects/components/src/utils/test/datagrid/filter-utils.ts, projects/components/src/utils/test/datagrid/vcd-datagrid.wo.ts, projects/components/src/utils/test/widget-object/angular-widget-finder.ts, projects/components/src/utils/test/widget-object/angular-widget-object.spec.ts, projects/components/src/utils/test/widget-object/angular-widget-object.ts, projects/components/src/utils/test/widget-object/cypress-widget-finder.ts, projects/components/src/utils/test/widget-object/cypress-widget-object.ts, projects/components/src/utils/test/widget-object/find-cypress-widget.ts, projects/components/src/utils/test/widget-object/widget-object.ts
-   [X] Bugfix
The Widget object finder was trying to imply the type of the widget object it was locating. This meant it had to both imply the widget type but also the type of the underlying driver. …
=> Fixed //@ ts-ignore issue with the Widget Object pattern

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/examples/src/components/datagrid/datagrid-action-menu-tracking-example.component.html, projects/examples/src/components/datagrid/datagrid-action-menu-tracking-example.component.scss, projects/examples/src/components/datagrid/datagrid-action-menu-tracking-example.component.ts, projects/examples/src/components/datagrid/datagrid-action-menu-tracking.example.module.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
There are cases when it is needed to have a reference to the
action menu that is positioned above the grid, in the grid action tool bar.
This action menu may be dynamically added to / removed from the DOM based
on the actions availability.
-   [x] Bugfix
-   [ ] Documentation …
=> Add `mainActionMenu` property to `DatagridComponent`

projects/components/CHANGELOG.MD, projects/components/src/action-menu/action-menu.component.spec.ts, projects/components/src/action-menu/action-menu.component.ts, projects/components/src/action-search-provider/action-search.provider.spec.ts, projects/components/src/action-search-provider/action-search.provider.ts, projects/examples/src/app/components/action-menu/search/action-menu-search-example.component.html, projects/examples/src/app/components/action-menu/search/action-menu-search-example.component.ts
-   [X] Tests for the changes have been added (for bug fixes/features)
-   [X] Bugfix
Fix the following bug...
Showing grouped actions with no children in the quick search as a search result. Eg., If a vapp action called
'Add' has no actions as its children, it is still …
=> Vapp add action bug fix

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/action-menu/action-menu.component.html, projects/components/src/action-menu/action-menu.component.spec.ts, projects/components/src/action-menu/action-menu.component.ts, projects/components/src/action-search-provider/action-search.provider.ts, projects/components/src/common/interfaces/action-item.interface.ts, projects/components/src/dropdown/dropdown.component.html, projects/components/src/dropdown/dropdown.component.ts, projects/examples/src/app/components/action-menu/hide-disable/action-menu-hide-disable-example.component.html, projects/examples/src/app/components/action-menu/hide-disable/action-menu-hide-disable-example.component.ts
-   [X] Bugfix
Some of the actions, particularly the visibility static actions depend
on values other than selected entities, like the response from async
requests. For such cases, we need to accept …
=> Update the action availability to accept observables

projects/components/CHANGELOG.MD, projects/components/src/common/interfaces/select-option.ts, projects/components/src/form/form-select/form-select.component.html, projects/components/src/form/form-select/form-select.component.spec.ts, projects/examples/src/components/form-input/form-input-components.examples.module.ts, projects/examples/src/components/form-input/form-select-disabled.example.component.html, projects/examples/src/components/form-input/form-select-disabled.example.component.ts, projects/examples/src/components/form-input/form-select.example.module.ts
Signed-off-by: Yoana Boyanova <yboyanova@vmware.com
-   [ ] Bugfix
HTML's option object has a feature where an option is not selectable
by the user when you set the disabled attribute. vcd-form-select …
=> Add new feature for disabling options in vcd-form-select

cypress/support/index.js, projects/components/CHANGELOG.MD, projects/components/src/utils/test/widget-object/angular/angular-widget-finder.ts, projects/components/src/utils/test/widget-object/angular/angular-widget-object-element.ts, projects/components/src/utils/test/widget-object/angular/angular-widget-object.spec.ts, projects/components/src/utils/test/widget-object/cypress/cypress-widget-finder.ts, projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.spec.ts, projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.ts, projects/components/src/utils/test/widget-object/widget-object.ts
-   [X] Bugfix
The widget finder was ignoring most of the arguments given to `findOptions` in a call to `findWidget`. This meant we couldn't find widgets by text or index. This patches the bug.
Also, …
=> Allows findWidget to use all given findOptions and adds clear to widget object

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/quick-search/quick-search.component.html, projects/components/src/quick-search/quick-search.component.spec.ts, projects/components/src/quick-search/quick-search.component.ts, projects/components/src/quick-search/quick-search.provider.ts, projects/examples/src/components/quick-search/quick-search-hide-empty-section-example.component.ts
-   [ ] Bugfix
Changes quick search to only display one "no results" section at the very top when all sections have returned no results. 
Loaded to VCD_UI, and searched for "aaaaaa". Observed one …
=> Removed hideWhenEmpty and creates a single no results section

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/action-menu/action-menu.component.spec.ts, projects/components/src/action-menu/action-menu.component.ts, projects/components/src/common/interfaces/action-item.interface.ts, projects/components/src/datagrid/datagrid.component.spec.ts, projects/examples/src/app/components/action-menu/search-debounce/action-menu-search-debounce.example.component.ts, projects/examples/src/app/components/action-menu/search/action-menu-search-example.component.ts, projects/examples/src/app/components/action-menu/with-separators/action-menu-with-separators.example.component.html, projects/examples/src/components/datagrid/datagrid-action-menu-tracking-example.component.ts, projects/examples/src/components/datagrid/datagrid-activity-reporter.example.component.ts, projects/examples/src/components/datagrid/datagrid-link.example.component.ts
-   [ ] Bugfix
Callbacks with selected entities are only meant for contextual actions and users were using them for static actions also. So now with this change, when a user tries to assign values to …
=> Change Availability of static actions to not accept CBs

projects/components/CHANGELOG.MD, projects/components/src/data-exporter/data-exporter.component.html, projects/components/src/data-exporter/data-exporter.component.scss, projects/components/src/data-exporter/data-exporter.component.spec.ts, projects/components/src/data-exporter/data-exporter.component.ts
-   [X] Bugfix
The data exporter was not accessible from the keyboard. Specifically, the exported columns could not be changed using the keyboard.
1. Click export data
2. Tab to select all columns
3. …
=> Makes the data-exporter keyboard accessible

projects/components/CHANGELOG.MD, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.scss
-   [X] Bugfix
Fix the width occupied by containing inputs of number with unit input
component so that they take up the container with and align with other
inputs.
Number with unit inputs are misaligned …
=> Fix the styling issues of number with unit input

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.spec.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.widget-object.ts, projects/examples/src/components/form-input/number-with-unit-form-input.example.component.ts
-   [X] Bugfix
1. Fixes a bug where if the unlimitedValue was 0, it was impossible to set the form as required. This is because null was passed through in `getValue()` outputting 0, which was the same …
=> Fixes bugs with the number with unit form

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/action-menu/action-menu.component.spec.ts, projects/components/src/action-menu/action-menu.component.ts, projects/components/src/common/interfaces/action-item.interface.ts, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/datagrid/index.ts, projects/components/src/datagrid/interfaces/datagrid-action-display.interface.ts, projects/components/src/datagrid/interfaces/datagrid-column.interface.ts, projects/components/src/sharing-modal/tabs/sharing-modal-tab.component.html, projects/components/src/sharing-modal/tabs/sharing-modal-tab.component.ts, projects/examples/src/app/components/action-menu/contextual-actions/action-menu-contextual-actions-example.component.ts, projects/examples/src/app/components/action-menu/hide-disable/action-menu-hide-disable-example.component.ts, projects/examples/src/app/components/action-menu/search-debounce/action-menu-search-debounce.example.component.ts, projects/examples/src/app/components/action-menu/search/action-menu-search-example.component.ts, projects/examples/src/app/components/action-menu/static-and-contextual-actions/action-menu-static-and-contextual-actions-example.component.ts, projects/examples/src/components/datagrid/datagrid-action-menu-tracking-example.component.html, projects/examples/src/components/datagrid/datagrid-action-menu-tracking-example.component.ts, projects/examples/src/components/datagrid/datagrid-link.example.component.ts
-   [ ] Bugfix
This change does the following:
- ActionDisplayConfig of ActionMenuComponent does not accept `featuredCount` when actions are displayed inline as there is no difference between featured …
=> Improve the action display config interface for datagrid

projects/components/CHANGELOG.MD, projects/components/src/action-menu/action-menu.component.spec.ts, projects/components/src/common/interfaces/action-item.interface.ts, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/interfaces/datagrid-action-display.interface.ts
-   [ ] Bugfix
It does the following:
- Make the buttonContents property optional for inline display configuration of contextual actions
- Make the position …
=> Mark some action display config interface props as optional

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/lib/directives/responsive-input/responsive-input.directive.spec.ts, projects/components/src/lib/directives/responsive-input/responsive-input.directive.ts
This PR also introduces a change to mark button contents as optional for inline display config of contextual actions.
-   [X] Bugfix
On large modals, most of the labels that are not very long are …
=> Make labels on large modals take 1/4th of container space 

projects/components/src/datagrid/datagrid.component.ts
Signed-off-by: Ryan Bradford <bradfordr@vmware.com>
-   [ ] Bugfix
-   [X] Refactoring (no functional changes, no api changes)
In Clarity 3, there was a bug where when Ivy was disabled, filtering the grid could cause the rows to disappear. The workaround was to …
=> Removes calls to grid.organizer.resize()

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/action-menu/action-menu.component.spec.ts, projects/components/src/action-menu/action-menu.component.ts, projects/components/src/common/interfaces/action-item.interface.ts, projects/components/src/datagrid/interfaces/datagrid-action-display.interface.ts, projects/examples/src/app/components/action-menu/contextual-actions/action-menu-contextual-actions-example.component.html, projects/examples/src/app/components/action-menu/contextual-actions/action-menu-contextual-actions-example.component.ts, projects/examples/src/app/components/action-menu/with-separators/action-menu-with-separators.example.component.ts, projects/examples/src/components/datagrid/datagrid-link.example.component.ts
-   [ ] Bugfix
ActionDisplayConfig of ActionMenuComponent does not accept featuredCount when actions are displayed in a dropdown as there is no way to display featured actions separately in a dropdown …
=> ActionDisplayConfig of ActionMenuComponent accepts featuredCount only when the actions are displayed inline

projects/components/CHANGELOG.MD, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.spec.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts
-   [X] Bugfix
If the number with unit showUnlimitedValue was set to false and the user typed in "-1", the form would try and select the unlimited option. This would cause the form to appear disabled …
=> Fixes bug with selecting unlimited in the number with unit

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/assets/resources/en.properties, projects/components/src/quick-search/quick-search.component.html, projects/components/src/quick-search/quick-search.component.scss, projects/components/src/quick-search/quick-search.component.spec.ts, projects/components/src/quick-search/quick-search.component.ts, projects/components/src/quick-search/quick-search.provider.ts, projects/components/src/quick-search/quick-search.wo.ts, projects/components/src/utils/test/widget-object/angular/angular-widget-object-element.ts, projects/examples/src/components/quick-search/nested-providers/quick-search-nested-providers.example.component.ts
-   [ ] Bugfix
Adds icons next to quick search section titles.
1. Linked to VCD, searched for "a" and observed the following results:
2. 
-   [ ] Yes
-   [X] No
=> Add optional icons next to quick search titles

projects/components/CHANGELOG.MD, projects/components/src/datagrid/datagrid.component.spec.ts
-   [ ] Bugfix
-   [x] Other... Please describe:
If there is no change in the datagrid selection the getter method `datagridSelection`
should return the same array reference. This is needed for performance optimization
so that angular …
=> Add unit test to ensure datagridSelection returns same reference

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/action-menu/action-menu.component.spec.ts, projects/components/src/action-menu/action-menu.component.ts
-   [ ] Bugfix
-   [x] Other... Please describe: Optimization
Currently on any reference input change for `actions` and `selectedEntities`
the component is doing redundant computations and emits `actionsUpdate`
even though there is no …
=> Optimize ActionMenuComponent for less processing on input change

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/form/form-select/form-select.component.html, projects/components/src/form/form-select/form-select.component.scss, projects/components/src/form/form-select/form-select.component.ts, projects/examples/src/components/form-input/form-select.example.component.html
It also allows hints that contain newlines to be displayed
as actual new lines, such as in `<pre>` blocks.
`@Input`s for description and hints like 
* Go to http://localhost:4200/formSelect/example/form-select
* Verify that the hint displays with new lines displayed as real line breaks
* Verify that the description displays below
Also loaded vcd_ui and tested in on a vcd-form-select
* Initially, the hint dropdown ends up on a new line because `vcd.scss` is trying to display …
=> Adds description and hint to form-select

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/action-search-provider/action-search.provider.ts, projects/components/src/quick-search/quick-search.component.html, projects/components/src/quick-search/quick-search.component.scss, projects/components/src/quick-search/quick-search.component.spec.ts, projects/components/src/quick-search/quick-search.component.ts, projects/components/src/quick-search/quick-search.dataui.ts, projects/components/src/quick-search/quick-search.module.ts, projects/components/src/quick-search/quick-search.wo.ts, projects/examples/src/components/quick-search/filters/quick-search-filters.example.component.ts
-   [X] Bugfix
1. Entirely changes the way quick search filters are displayed. There is now a series of dropdown buttons where you can select filter types and then they display as bubbles below the …
=> Reworks quick search filters + loading indicator

projects/components/CHANGELOG.MD, projects/components/src/quick-search/drawer/drawer.component.scss
-   [X] Bugfix
Pinned quick search was appear above modals. This caused a few visual errors. This adjusts the z-index of the quick search pinned container to be below modals.
1. Loaded components into …
=> Fix pinned quick search appearing above modals

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/quick-search/quick-search.component.html, projects/components/src/quick-search/quick-search.component.spec.ts, projects/components/src/quick-search/quick-search.component.ts, projects/components/src/quick-search/quick-search.service.ts, projects/examples/src/assets/our-translations.json, projects/examples/src/components/quick-search/filters/quick-search-filters.example.component.html, projects/examples/src/components/quick-search/filters/quick-search-filters.example.component.ts
-   [ ] Bugfix
-   [X] Refactoring (no functional changes, no api changes)
Filters are now configured through the search service rather than through quick search itself. In addition, the search service now has methods to select a filter value and to test if the …
=> Configure quick search filters through service

projects/examples/src/components/datagrid/datagrid-action-display-config.example.component.html, projects/examples/src/components/datagrid/datagrid-action-display-config.example.component.scss, projects/examples/src/components/datagrid/datagrid-action-display-config.example.component.ts, projects/examples/src/components/datagrid/datagrid-action-display-config.example.module.ts, projects/examples/src/components/datagrid/datagrid-link.example.component.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
-   [ ] Bugfix
-   [X] Example website changes
To make it clear for the users of our library about different options
available to display actions and also show them the input object that
has to be passed to datagrid to customize the …
=> Add example to show 'display configurations' for contextual actions in data grid

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/quick-search/quick-search.component.spec.ts, projects/components/src/quick-search/quick-search.service.spec.ts, projects/components/src/quick-search/quick-search.service.ts, projects/examples/src/components/quick-search/filters/quick-search-filters.example.component.html, projects/examples/src/components/quick-search/filters/quick-search-filters.example.component.ts
The changes include:
-   [x] Bugfix
-   [x] Code style update (formatting, local variables)
- add optional `order` field to the filters so they can be ordered
- add function  `insertInOrder` in order to reuse code …
=> Quick Search fixes and improvements

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/data-exporter/data-exporter.component.spec.ts, projects/components/src/data-exporter/data-exporter.wo.ts, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/quick-search/quick-search.component.spec.ts, projects/components/src/quick-search/quick-search.wo.ts, projects/components/src/sharing-modal/sharing-modal.component.spec.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/components/src/utils/test/widget-object/angular/angular-widget-object.spec.ts, projects/components/src/utils/test/widget-object/widget-object.ts
WidgetObject#internalFactory has caused confusion for developers. It caused a different way to interact with components depending on whether you're inside a `WidgetObject` or you're within a test (stepdef or unit test). 
To avoid this confusion, we now always expose `WidgetObjectElement`s and callers call `unwrap()` on their own if they want to use the `T` functionality that is specific to the testing framework being used.
Also removed the explicit return types for WidgetObject methods since they will all (mostly) return …
=> Removes internalFactory from WidgetObject

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/action-menu/action-menu.component.html, projects/components/src/common/interfaces/action-item.interface.ts, projects/components/src/dropdown/dropdown.component.html, projects/examples/src/app/components/action-menu/action-menu.examples.module.ts, projects/examples/src/app/components/action-menu/data-ui-attribute/action-menu-data-ui-example.component.html, projects/examples/src/app/components/action-menu/data-ui-attribute/action-menu-data-ui-example.component.scss, projects/examples/src/app/components/action-menu/data-ui-attribute/action-menu-data-ui-example.component.ts, projects/examples/src/app/components/action-menu/data-ui-attribute/action-menu-data-ui-example.module.ts, projects/examples/src/assets/our-translations.json
-   [ ] Bugfix
-   [X] Other... Please describe: Add action textKey as `data-ui` attribute on action button elements
Add action textKey as `data-ui` attribute on action button elements to use data-ui attributes as css selectors for …
=> Add action textKey as `data-ui` attribute on action button elements

projects/components/CHANGELOG.MD, projects/components/src/assets/resources/en.properties, projects/components/src/quick-search/quick-search.component.html
[i18n] The string "Filter By" in the search dialog is hardcoded.
The string "Filter By" in the search dialog is hardcoded.
Add translation
1. Change browser language to fr-FR, login VMware Cloud Director provider UI.
2. Click on the search icon.
3. Check the translation of the string "Filter By".
JIRA: COR-8604
-   [x] Bugfix …
=> [i18n] The string "Filter By" in the search dialog is hardcoded.

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/sharing-modal/users-groups-orgs-sharing-modal.directive.ts, projects/components/src/utils/index.ts, projects/components/src/utils/rest/rest-query-search.client.ts
Signed-off-by: Ria Mahoney <mpatrice@vmware.com>
-   [ ] Bugfix
* Sends data in RECORDS format instead of IDRECORDS
* Exports FilterBuilder
* New Sharing Modal requires filter on search/dropdown
* …
=> Sharing Modal Format and Search

projects/components/CHANGELOG.MD, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.html
Making number-with-unit-form-input read-only label
visibility consistent with the non-read-only code.
Testing Done:
Built and manually tested within VCD.
Confirmed label is no longer taking space when empty.
Signed-off-by: Bryan Bozzi <bryanv@vmware.com>
=> Updating number-with-unit input read-only label.

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.spec.ts, projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.ts
-   [x] Bugfix
Fixes a bug where if you tried to pass `{index:0}` when calling a `CypressWidgetObjectElement#get(...)`, the index would be ignored and you'd still get all the matching elements from your query (instead of just the first one)
No manual testing but unit test was adjusted to use `index: 0.
-   [x] No
=> Fix bug when passing index=0 to CypressWidgetObjectElement.get

projects/route-analyzer/CHANGELOG.MD, projects/route-analyzer/package.json, projects/route-analyzer/src/lib/gen-route-builder.spec.ts, projects/route-analyzer/src/lib/gen-route-builder.ts, projects/route-analyzer/src/lib/route-analyzer.ts, projects/route-analyzer/src/lib/route-info.ts, projects/route-analyzer/src/public-api.ts
Adds a `regex` property to objects created by route-analyzer
This regex can be tested against existing URLs to see if a URL matches a route.
This is going to be used in VCD UI automated smoke tests to find the HTML tag name for any given URL
None, unit testing only
-  [x] Feature
-  [x] Version bump
-   [x] No
-   [x]  Tests for the changes have been added (for bug fixes / features)
=> Add regex to route objects created by route-analyzer

.github/workflows/ci-cd.yml, projects/components/CHANGELOG.MD, projects/components/src/lib/directives/show-clipped-text.directive.spec.ts, projects/components/src/lib/directives/show-clipped-text.directive.test-helper.ts, projects/components/src/lib/directives/show-clipped-text.directive.ts, projects/examples/src/app/components/show-clipped-text/hide/hide-clipped-text-example.component.html, projects/examples/src/app/components/show-clipped-text/hide/hide-clipped-text-example.component.scss, projects/examples/src/app/components/show-clipped-text/hide/hide-clipped-text-example.component.ts, projects/examples/src/app/components/show-clipped-text/hide/hide-clipped-text-example.module.ts, projects/examples/src/app/components/show-clipped-text/show-clipped-text-examples.module.ts
-   [x] Bugfix
Bugzilla bug: https://bugzilla.eng.vmware.com/show_bug.cgi?id=2881645
When the component is destroyed the tooltip still remains visible.  
The solution is to hide Tooltip on ngOnDestroy …
=> The Tooltip  is visible when the component is destroyed

.github/workflows/ci-cd.yml, README.md
This is copying the work from [live-docs](https://github.com/vmware/live-docs/pull/42)
Checking the actual package.json version was causing problems
when using versions such as `3.0.0-dev.1` because the action we used wasn't able to tell that `3.0.0-dev.2` was higher
We don't check versions anymore. Users are responsible for updating
package.json to a valid version and an error will occur if, for
example, they add the magic string but forget to bump package.json.
The magic strings are described in the [Publishing section of our  README.md file](https://github.com/vmware/vmware-cloud-director-ui-components/pull/406/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R75-R80)
Created multiple commits, each with the following modifications, which were removed for the …
=> Publish by commit message

projects/components/src/lib/directives/show-clipped-text.directive.ts, projects/components/src/utils/test/widget-object/angular/angular-widget-object-element.ts, projects/components/src/utils/test/widget-object/angular/angular-widget-object.spec.ts, projects/components/src/utils/test/widget-object/cypress/cypress-widget-finder.ts, projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.spec.ts, projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.ts, projects/components/src/utils/test/widget-object/widget-object.ts
Signed-off-by: Bryan Bozzi <bryanv@vmware.com>
-   [ ] Bugfix
-   [x] Other... Please describe:
Testing framework changes
Implemented the select function to select options.
Added exactText to FindElementOptions so that
we can find …
=> Allow WidgetObjects to  find elements by exact text - allow selecting options from select elements.

projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.spec.ts, projects/components/src/datagrid/datagrid.component.ts, projects/components/src/utils/test/datagrid/datagrid.wo.ts, projects/examples/src/components/datagrid/datagrid-is-row-selectable-example.component.html, projects/examples/src/components/datagrid/datagrid-is-row-selectable-example.component.ts, projects/examples/src/components/datagrid/datagrid-is-row-selectable-example.module.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
Clarity's datagrid supports clrDgSelectable, which disable/enable row selectability. This change will allow VCD datagrid to use clrDgSelectable. It will take a callback function to calculate row's selectability.
Signed-off-by: Xuanvinh Vu <xvu@vmware.com>
-   [ ] Bugfix
-   [ ] Example …
=> Add the ability to disable datagrid's row selection

projects/components/package.json, projects/i18n/package.json
See https://github.com/vmware/vmware-cloud-director-ui-components/runs/5672638746?check_suite_focus=true
[publish @vcd/ui-components@latest]
[publish @vcd/i18n@latest]
> npm ERR! Invalid version: "12.0"
=> Fix publishing of @vcd/ui-components and @vcd/i18n

projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.ts
The CypressWidgetObject implementation of parents() was returning
all parents that matched the query instead of the closest parent.
Testing Done:
Manually confirmed the fix with Cypress tests in VCD.
Signed-off-by: Bryan Bozzi <bryanv@vmware.com>
-   [x] Bugfix
-   [ ] Example website …
=> Fix CypressWidgetObject parents() function returning many parents.

projects/components/src/dropdown/dropdown.component.scss
Clarity buttons have max-width 18rem, while nested dropdowns have a hardcoded 15rem. This breaks the alignment when both elements are in the same container and the button contains a longer text (expanding over the 15rem).
This commit moves the max-width constraint from the nested dropdown into its parent element, ensuring the items remain always aligned.
Signed-off-by: Davi Barreto <dbarreto@vmware.com>
-   [x] Bugfix
-   [ ] Refactoring …
=> Fix alignment in nested dropdowns

package-lock.json, package.json
We had been previously running ng lint which runs it on the entire
project and can take up to 5 minutes.
`ng lint` cannot be used with `lint-staged` because `lint-staged` will just
append the staged files to the end of the command, so it would look like
`ng lint --fix --lint-file-patterns file1 file2 file3`
However, `ng lint` would expect it to be
`ng lint --fix --lint-file-patterns=file1 --lint-file-patterns=file2 --lint-file-patterns=file3`
See https://github.com/angular-eslint/angular-eslint/issues/421#issuecomment-1100076149
Committed a single file and verified that eslint runs quickly, under 15 seconds. See below
-   [x] Build related changes
-   [x] No
=> Lint only staged files in pre-commit hook

projects/components/CHANGELOG.MD, projects/components/package.json
Start using v12 to match v12 of Clarity and Angular so that we won't need a compatibility table.
Running the application and verifying each grid example
-   [x] No
=> [publish @vcd/ui-components] Start tracking Angular major version

projects/components/CHANGELOG.MD, projects/components/src/utils/test/widget-object/cypress/cypress-widget-finder.ts, projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.spec.ts, projects/components/src/utils/test/widget-object/cypress/cypress-widget-object-element.ts
-   [X] Bugfix
Calls to WidgetObjectElement.findWidget weren't always chained off the correct result. If you first make a call to `.get` and then findWidget, it would find the widget in whatever the …
=> Fixed bug in Cypress findWidget

package-lock.json, package.json, projects/components/package.json, projects/components/src/common/subscription/subscription-tracker.ts, projects/components/src/datagrid/filters/datagrid-filter.ts
We updated ui-components rxjs version to 7.4.0 but in vcd-ui that version causes a lot
of breaking changes which will need to be handled in a separate future time slot.
- vcd-ui currently uses rxjs@6.6.3 and wherever the SubscriptionTracker is used there errors:
"TypeError: _a.bind is not a function"
"TypeError: fn.call is not a function"
- 731 unit tests are also failing
- The simplest solution is to revert to the previous rxjs version that ui-components used - 6.5.5
- This fixes all the above mentioned issues
[publish @vcd/ui-components]
Signed-off-by: Georgi Atanasov <georgi.atanasov147@gmail.com>
-   [ ] Examples have been added / updated (for bug fixes …
=> Publishing ui-components with rxjs version 6.5.5

projects/components/src/form/base-form-control.ts, projects/components/src/form/form-checkbox/form-checkbox.component.ts, projects/components/src/form/form-input/form-input.component.ts, projects/components/src/form/form-select/form-select.component.html, projects/components/src/form/form-select/form-select.component.spec.ts, projects/components/src/form/form-select/form-select.component.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts, projects/examples/src/components/form-input/form-input-components.examples.module.ts, projects/examples/src/components/form-input/form-select-validation.example.component.html, projects/examples/src/components/form-input/form-select-validation.example.component.ts, projects/examples/src/components/form-input/form-select.example.module.ts
The `FormSelectComponent` was hardcoded to use its control's `.value` to be passed to the translation service (along with its key) to display the error messages.
Now, instead of passing its `.value`, it will use the values provided by the `ValidationErrors`'s values. The translation parameters could be `any` or an array of `any`. This get pass to the TranslationService to be used for translation.
```typescript
// My custom validator
function isAllGoodValidator(control: FormControl) {
if (control.value != "SaulGoodman") {
return {'some.error.key': [ 'all', 'is', 'man', 'good', 'It']}
}
return null;
}
// In en.properties
// some.error.key={4} {1} {0} {3}, {2}!
```
The select above would show the following error message: `It is all good, man!`
Signed-off-by: Xuanvinh Vu xvu@vmware.com
Please …
=> FormSelectComponent not taking in translation params

projects/components/src/dropdown/dynamic-dropdown-position.directive.ts, projects/components/src/dropdown/dynamic-dropdown-position.spec.ts
BrowserAnimationsModule causes the angular routing to delay removing old DOM elements that were present in previous routes. This leads to cases where we have two `.content-area` elements, and the `DynamicDropdownPositionDirective` matches the one which belonged to the old route and thus later gets destroyed.
This commit makes the `DynamicDropdownPositionDirective` compute the contentAreaElement just before positioning the dropdown menu, ensuring it picks the relevant `.content-area` at the time of its opening.
Signed-off-by: Davi Barreto <dbarreto@vmware.com>
-   [ ] Changelog has been …
=> Fix vcd-action-menu matching the wrong content-area

.github/workflows/ci-cd.yml
See error run https://github.com/vmware/vmware-cloud-director-ui-components/actions/runs/3524378013/jobs/5909738240
> nx run examples:deploy --no-build
>  NX   Property 'cname' does not match the schema. 'false' should be a 'string'.
>  NX   Running target "examples:deploy" failed
Ran ` npx nx deploy examples --no-build  --cname=` locally without errors
-   [ ] Bugfix
-   [x] CI related changes
-   [ ] Yes
-   [ ] …
=> Fix schema validation error when deploying

.github/workflows/ci-cd.yml, projects/components/CHANGELOG.MD, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.spec.ts, projects/components/src/form/number-with-unit-input/number-with-unit-form-input.component.ts
Fix NumberWithUnitFormInputComponent not restoring its value after un-toggling "unlimited"
NumberWithUnitFormInputComponent has a feature which restores the input value once the "unlimited" checkbox is turned off. However, that feature seems to have regressed in some of the past refactorings. This commit fixes the restore feature and adds a test to prevent future regressions.
A note on replacing `lastRealValue` with `lastTextValue`: older implementations (before a couple refactorings) were calling `.setValue` on a nested `vcd-form-input` and that is why we needed the computed real value. Currently that is no longer the case, and instead, the `getValue` method computes the real value from the text input. Hence replacing `lastRealValue` with `lastTextValue` and restoring it instead. …
=> Fix NumberWithUnitFormInputComponent not restoring its value after un-toggling "unlimited"

projects/components/CHANGELOG.MD, projects/components/src/data-exporter/data-exporter.component.html
-   [x] Bugfix
Users were unable to tab to the info signposts to activate them and view their content. Removing the clr-icon to make the signposts consistent with Clarity examples fixes the tabbing.
In …
=> Tab signposts

projects/components/CHANGELOG.MD, projects/components/src/data-exporter/index.ts
This is going to be used to generate reports from vcd_ui
Tested by using `npm pack` and then istalling the tar file locally on vcd_ui and making sure it can be used. See video attached to PR.
Expose CsvExporterService
* Built `@vcd/ui-components`
* created an npm package using `npm pack` from the `dist` folder
* Installed the tar file using npm install from vcd_ui's `content/core`
* Used the exporter to generate a CSV.
https://user-images.githubusercontent.com/549331/211342405-ce9e5011-4b6b-4239-a247-54f6d7868412.mov
-   [x] No
=> Exposing CsvExporterService

projects/route-analyzer/CHANGELOG.MD, projects/route-analyzer/src/lib/route-analyzer.ts
Before this commit, the route-analyzer would search for modules by their basenames (eg. my-module.ts). This could match the wrong module in cases where we had two module files with same file name but in different folders.
This change fixes the issue by matching absolute paths instead of only basenames.
Signed-off-by: Davi Barreto <dbarreto@vmware.com>
-   [x] Bugfix
This change makes the route-analyzer correctly handle duplicate file names by using the absolute path.
a. Run the old route-analyzer locally …
=> Fix route-analyzer not handling equal module basenames

projects/route-analyzer/CHANGELOG.MD, projects/route-analyzer/src/lib/route-analyzer.ts
A previous commit introduced a regression where the route analyzer was unable to find modules on windows machines. The issue was that the new strings generated by nodejs were windows like, but the remaining script logic uses posix.
Fixed by ensuring we always convert to posix after joining the absolute paths.
-   [x] Bugfix
Fixes the route analyzer for windows users
1. On a windows machine
2. Place the fixed route-analyzer on VCD UI
3. Run the route-analyzer
4. Verify no errors are thrown
-   [x] No
=> Fix route-analyzer not finding modules on windows machines

projects/components/CHANGELOG.MD, projects/components/src/assets/resources/en.properties, projects/components/src/quick-search/quick-search.component.html
The aria-label property was wrongly hard coded as "home". Replaced it with a dynamic string which reflects the filter's label.
-   [x] Bugfix
Adds the correct aria-label to the quick search filter remove buttons
1. `npx nx serve examples`
2. Navigate to http://localhost:4200/quickSearch/example/filters
3. Click "Here" to open the quick search
4. Add a filter
5. Turn screen reader on and navigate to the delete filter button "x"
6. Verify the screen reader states `Stop filtering by "<name of filter>"`
-   [ ] Yes
-   [x] No
=> Fix incorrect aria-label on remove quick search filter buttons

projects/components/CHANGELOG.MD, projects/components/src/assets/resources/en.properties, projects/components/src/components.module.ts, projects/components/src/lib/directives/aria-activedescendant/aria-active-descendant.directive.ts, projects/components/src/lib/directives/aria-activedescendant/aria-active-descendant.service.ts, projects/components/src/lib/directives/aria-activedescendant/aria-activedescendant.module.ts, projects/components/src/lib/directives/aria-activedescendant/index.ts, projects/components/src/lib/directives/index.ts, projects/components/src/quick-search/quick-search.component.html, projects/components/src/quick-search/quick-search.component.scss, projects/components/src/quick-search/quick-search.component.ts, projects/components/src/quick-search/quick-search.module.ts, projects/examples/src/components/quick-search/quick-search-content-projection.example.component.html, projects/examples/src/components/quick-search/quick-search-hide-empty-section-example.component.html, projects/examples/src/components/quick-search/quick-search-sync-async.example.component.html
-   [x] Bugfix
Fixes quick-search component accessibility issues:
1. Missing dialog name
2. Missing filters 'labeled by' attribute
3. Results section inaccessibility by screen reader
4. Missing label of …
=> Fix accessibility issues related to quick-search component

package-lock.json, package.json, projects/components/CHANGELOG.MD
-   [X] Build related changes
There's an issue publishing the tarball presumably because of a dependency. This change reverts package.json and package-lock.json to its 13.0.1-dev.7 contents. There was a transitive dependency `macos-release` that _seemed_ to be out of date when I tried building on my macOS Ventura machine (13.1) so I added an explicit `devDependency` to its latest version via npm install. It's possible it or any other dependency that was upgraded is causing the issue. 
-   [X] No
=> Reverting package.json and package-lock.json

projects/components/CHANGELOG.MD, projects/components/src/form/form-select/form-select.component.html, projects/components/src/form/form-select/form-select.component.spec.ts
-   [X] Bugfix
Use aria-describedby  attribute for description in the vcd-form-select input subtext when showError is false.
1. npx nx serve
2. Turn on your screen reader
3. Navigate to …
=> [a11y] Add aria-describedby attribute to the Form Select component

projects/components/CHANGELOG.MD, projects/components/src/dropdown/dynamic-dropdown-position.directive.ts
[VACE-4391] Extensibility framework cause the actions menu to be redrawn numerous times causing tens/hundreds API calls to external systems
Issue:
When the action menus in vcd get refreshed with new items (replacing) the action menu "jumps" because there is not enough space for the action menu to be redrawn.
Fix:
If there is not enough space for the action menu to be redrawn, show it at the middle of the screen
Testing Done:
- Install common components to vcd and verify the action menu position remains constant  if it doesn't have enough space.
What kind …
=> [VACE-4391] Extensibility framework cause the actions menu to be redrawn numerous times causing tens/hundreds API calls to external systems

projects/examples/src/components/quick-search/quick-search-hide-empty-section-example.component.html
It was not needed for the example and referenced an invalid value from the `form.value`
It didn't fail compilation before  typed forms
-   [x] Bugfix
Built the app in production mode so templates get compiled and tested. The new typed forms caught the problem.
=> Remove unused placeholder input in quick search example

package-lock.json, package.json, projects/route-analyzer/CHANGELOG.MD, projects/route-analyzer/ng-package.json, projects/route-analyzer/package.json, projects/route-analyzer/src/lib/utils.ts
Updates the version of route analyzer since the update to ng 15 made changes to the route analyzer to where we were calling `.decorators`.
Went ahead and removed the deprecated `@wessberg/ts-evaluator`
* Built the package
* Packed its `dist` directory using `npm pack`
* Installed it into `vcd_ui` using the generated gzip file above (` npm i /Users/xxx/github/vcd-ui-common/dist/route-analyzer/vcd-route-analyzer-0.0.11.tgz`)
* Made sure that an error was not thrown. It was throwing the following error previously
```
TypeError: Cannot read property 'find' of undefined
at getTagName …
```
=> Bump route-analyzer to 0.0.11

projects/components/CHANGELOG.MD, projects/components/src/dropdown/dynamic-dropdown-position.directive.ts
-   [x] Bugfix
Position the dropdown action menue in the middle relative to the dropdown trigger button.
In some cases menu might be still cut off, because of the position rules of the positionTop …
=> [VACE-4563] VM actions menu is being cutoff at the top and not displaying Power On/Off action

projects/components/CHANGELOG.MD, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.scss, projects/components/src/datagrid/datagrid.component.ts
-   [X] Bugfix
-   [ ] Other... Please describe: CSS Style changes
Fixes a bug where the action column was too wide when using actions are displayed inline but there are no featured actions, therefore, no space should be reserved for …
=> Fix wider column for vcd-datagrid when actions are displayed with dropdown in a row 

projects/components/CHANGELOG.MD, projects/components/package.json, projects/widget-object/src/lib/angular/angular-widget-object-element.ts, projects/widget-object/src/lib/angular/angular-widget-object.spec.ts, projects/widget-object/src/lib/selector-util.ts
-   [x] Bugfix
Revert  `SelectorUtil.extractSelector` to what it was before `@vcd/widget-object` was split into its own lib. `extractSelector`'s signature now indicates that it could return undefined.
The specific case where this happens is when you call `el.get({text: 'some text'})` or `el.get({exactText: 'some text'})`. In that case, there is no `dataUiSelector` or `cssSelector` so the CSS selector is just `""`which will cause all nodes under the given `el` to be retrieved and then we'll filter for which ones contain text.
When moving `WidgetObject` out to its won library, I thought `extractSelector` expected to always find a selector but that was not true so throwing an Error was causing some tests to fail.
The compiler was complaining …
=> Revert behavior of SelectorUtil.extractSelector

projects/components/CHANGELOG.MD, projects/components/src/dropdown/dropdown.component.ts
Flattening of dropdowns with single action is causing issues, when the parent dropdown content is "dynamic".
It causes menus to jump when the parent contains
one child and few seconds alter 2+ child actions.
-   [x] Bugfix
-   [ ] …
=> Remove flattening of actions

README.md, projects/components/CHANGELOG.MD, projects/components/README.md, projects/components/src/assets/resources/en.properties, projects/components/src/quick-search/quick-search.component.html, projects/components/src/quick-search/quick-search.service.ts, projects/examples/src/styles.scss
-   [x] Bugfix
It is expected screen reader reads the search results amount when it is changed or the search is performed.
The change will add a new visually hidden (but not for screen readers) live aria with aria-live=polite attribute to make screen readers announce any change related to the results amount. Aria-live indicates that element will be updated and the politeness of the updates.
The accessibility team reached out to us with the issue that the old string isn't consistent with similar strings in other VMware products. The string is changed according to a discussion with an accessibility team member.
Testing Done:
- Open …
=> Add a number of results for screen readers

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/datagrid/datagrid.component.html, projects/examples/src/components/datagrid/datagrid-preserve-selection.example.component.ts, projects/examples/src/components/datagrid/datagrid-preserve-selection.example.module.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
VCD datagrid preserve selection input is not passed to Clarity datagrid. Clarity datagrid default behavior is to clear selection whenever the datagrid filter value is changed. By passing the preserve selection flag onto the Clarity datagrid, it will not clear the selection.
-   [x] Bugfix …
=> Pass the preserve selection value to Clarity datagrid

projects/components/CHANGELOG.MD, projects/components/src/lib/directives/show-clipped-text.directive.ts, projects/examples/src/app/components/show-clipped-text/focusing/focusing-clipped-text-example.component.html, projects/examples/src/app/components/show-clipped-text/focusing/focusing-clipped-text-example.component.scss, projects/examples/src/app/components/show-clipped-text/focusing/focusing-clipped-text-example.component.ts, projects/examples/src/app/components/show-clipped-text/show-clipped-text-examples.module.ts
-   [x] Bugfix
-   [x] Documentation content changes
The element with the assigned tooltip has to be accessible through the tab key.
There are cases when users don't use a screen reader, but use the tab key to navigate through the UI.
So if …
=> Fix tooltip keyboard a11y

projects/components/CHANGELOG.MD, projects/components/src/action-menu/action-menu.component.spec.ts, projects/components/src/action-menu/action-menu.component.ts, projects/components/src/dropdown/dropdown.component.html, projects/components/src/dropdown/dropdown.component.ts
The availability function for actions was not being used to hide the action. For example () => false would continue to show the action.
Wrote some unit tests and verified that they failed before the fix and passed after the fix.
Used the fixed version in our application and verified that it works in our product.
Bug Number: none
-   [x] Bugfix
-   [ ] …
=> Fix availability functionality for Action Menu

projects/examples/src/components/datagrid/datagrid-preserve-selection.example.component.ts, projects/route-analyzer/CHANGELOG.MD, projects/route-analyzer/README.md, projects/route-analyzer/package.json, projects/route-analyzer/src/cli.ts, projects/route-analyzer/src/lib/gen-route-segments.ts, projects/route-analyzer/src/lib/utils.ts
Generate constants for segments in routes
See comments in [README.md](https://github.com/juanmendes/vmware-cloud-director-ui-components/blob/dd91c33e1d8f3a78ab6bd19bbbd717f7d20c5f59/projects/route-analyzer/README.md#segments-typescript).
A list of strings representing each segment found in the application. Each
string is prepended with `segment_`.
If we use `/administration/access-control/users/:userId/general` as an example route, the following
variables will be generated
```typescript
export const segment_administration = 'administration';
export const segment_accessControl = 'access-control';
export const segment_users = 'users';
export const segment_userId = ':userId';
export const segment_general = 'general';
```
Your route definitions are the source of truth, just define them using …
=> Route analyzer segments

projects/components/CHANGELOG.MD, projects/components/src/datagrid/datagrid.component.html, projects/components/src/datagrid/datagrid.component.ts
Clarity introduced a new 'clrDgItemsTrackBy' input property which is used to compare the identity of selected grid items.
This new property has a different signature than the regular trackBy function, which is why we are taking our client's provided trackBy and wrapping it before passing into clrDgItemsTrackBy.
Link for the original bug: https://github.com/vmware-archive/clarity/issues/3936
Link for clarity's fix: https://github.com/vmware-clarity/ng-clarity/pull/539
-   [x] Bugfix
Fixes clarity's ["Datagrid uses wrong trackBy and breaks selection"](https://github.com/vmware-archive/clarity/issues/3936) bug by applying their [bugfix](https://github.com/vmware-clarity/ng-clarity/pull/539).
Tested against VCD's codebase.
-   [x] No
=> Fix clr-datagrid matching the wrong trackBy for selection comparison

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/assets/resources/en.properties, projects/components/src/datagrid/filters/datagrid-string-filter.component.html, projects/components/src/datagrid/filters/datagrid-string-filter.component.ts, projects/examples/src/components/datagrid/datagrid-string-filter-placeholder.example.component.ts, projects/examples/src/components/datagrid/datagrid.examples.module.ts
-   [x] Bugfix
-   [x] Documentation content changes
The absence of a placeholder led to the lack of accessibility. The
change will add a default "Find Items" placeholder which can be replaced
with a custom one.
- Open examples > …
=> Add placeholder to datagrid-string-filter

projects/components/CHANGELOG.MD, projects/components/package.json, projects/components/src/common/error/error-banner.component.spec.ts, projects/components/src/common/error/error-banner.component.ts, projects/components/src/common/error/error-banner.wo.ts, projects/examples/src/components/error/error-banner.example.component.html, projects/examples/src/components/error/error-banner.example.component.ts
-   [x] Bugfix
Please take a look at the distinct commits.
All changes are related to the ErrorBannerComponent and refer to:
* fix ExpressionChangedAfterItHasBeenCheckedError due to incorrect emit …
=> ErrorBanner errorMessage improvements
